// examples/angular/src/app/components/layout/layout.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { Header } from '../header/header';

@Component({
  selector: 'layout',
  imports: [RouterOutlet, Header],
  templateUrl: './layout.html',
  standalone: true,
  styles: [':host { display: contents; }'],
})
export class Layout {}

// examples/react/src/components/Layout/Layout.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { Outlet } from 'react-router-dom';
import Header from './Header/Header.tsx';

const Layout = () => {
    return (
        <>
            <Header />
            <div id='app' className='flex'>
                <Outlet />
            </div>
        </>
    );
};

export default Layout;
