// examples/react/src/pages/Payment/PaymentPage.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import {
    BasicPaymentProducts,
    CommunicationError,
    init,
    type OnlinePaymentSdk,
    type PaymentContext,
    type PaymentContextWithAmount,
    type SdkError,
    type SessionData
} from 'onlinepayments-sdk-client-js';
import { useNavigate } from 'react-router-dom';
import { useLoader } from '../../components/Loader/Loader.tsx';
import PaymentDetails from '../../components/PaymentDetails/PaymentDetails.tsx';
import ProductSelection from '../../components/ProductSelection/ProductSelection.tsx';
import AccountOnFileSelection from '../../components/AccountOnFileSelection/AccountOnFileSelection.tsx';
import Logo from '../../components/Logo/Logo.tsx';
import translations from '../../translations/translations.ts';
import StorageService from '@shared/services/StorageService';

const PaymentContextInitialState = {
    amountOfMoney: {
        amount: 1000,
        currencyCode: 'EUR'
    },
    countryCode: 'BE',
    isRecurring: false
} satisfies PaymentContextWithAmount;

const PaymentPage = () => {
    const sdk = useRef<OnlinePaymentSdk>(null);
    const [paymentContext, setPaymentContext] = useState<PaymentContext>(
        () => StorageService.getPaymentContext() ?? { ...PaymentContextInitialState }
    );

    const navigate = useNavigate();
    const { show, hide } = useLoader();

    const [isFormExpanded, setIsFormExpanded] = useState(true);
    const [errorMessage, setErrorMessage] = useState('');

    const [paymentMethods, setPaymentMethods] = useState<BasicPaymentProducts>();

    useEffect(() => {
        StorageService.clearItem('accountOnFileId');
        const sessionData = StorageService.getSessionData();

        if (!sessionData) {
            navigate('/');
        } else {
            sdk.current = init(sessionData as SessionData);
        }
    }, [navigate]);

    const handleExpandCollapse = useCallback(() => {
        setIsFormExpanded((prev) => !prev);
    }, []);

    const handleUnauthorizedError = (error: SdkError) => {
        if (error instanceof CommunicationError) {
            StorageService.clear();
            navigate('/');
        }
    };

    const fetchPaymentProducts = useCallback(
        (paymentDetails: PaymentContext) => {
            show();
            sdk?.current
                ?.getBasicPaymentProducts(paymentDetails)
                .then((basicPaymentProducts) => {
                    setPaymentMethods(basicPaymentProducts);
                    setErrorMessage('');
                })
                .catch((error: SdkError) => {
                    setErrorMessage(error?.message ?? '');
                    handleUnauthorizedError(error);
                    setPaymentMethods(undefined);
                })
                .finally(() => {
                    hide();
                });
        },
        // eslint-disable-next-line react-hooks/exhaustive-deps
        []
    );

    const setSelectedProduct = async (productId: number) => {
        show();
        const paymentProduct = await sdk?.current?.getPaymentProduct(productId, paymentContext as PaymentContext);

        if (!paymentProduct) {
            setErrorMessage(translations.payment_product_not_found);
            return;
        }

        StorageService.setPaymentProductId(paymentProduct.id);
        hide();

        return paymentProduct;
    };

    const handleProductSelection = async (id: string) => {
        const product = await setSelectedProduct(Number(id));

        if (product?.paymentMethod === 'card') {
            navigate(`/payment/credit-card/`);
        } else if (product?.paymentMethod === 'mobile' && product?.label === 'GOOGLEPAY') {
            navigate('/payment/google-pay/');
        } else {
            setErrorMessage(translations.this_demo_supports_only_card_payment_and_google_pay);
        }
    };

    const handleAccountOnFileSelection = async (id: string) => {
        const aof = paymentMethods?.accountsOnFile.find((aof) => aof.id === id);

        if (aof) {
            const product = await setSelectedProduct(aof.paymentProductId);

            StorageService.setAccountOnFileId(id);
            if (product?.paymentMethod === 'card') {
                navigate(`/payment/account-on-file/`);
            } else {
                setErrorMessage(translations.this_demo_supports_only_card_payment_and_google_pay);
            }
        }
    };

    const handlePaymentContextModelChange = <K extends keyof PaymentContext>(value: PaymentContext[K], prop: K) => {
        setPaymentContext?.((prev) => ({ ...(prev as PaymentContextWithAmount), [prop]: value }));
    };

    const handleSaveContextToStorage = useCallback(
        (context: PaymentContextWithAmount) => {
            StorageService.setPaymentContext(context);
            fetchPaymentProducts(context);
        },
        [fetchPaymentProducts]
    );

    return (
        <div className='page'>
            <Logo />
            <h1>{translations.payment_details}</h1>
            <p className='text-left'>{translations.order_details}</p>
            <PaymentDetails
                paymentContext={paymentContext}
                isFormExpanded={isFormExpanded}
                onExpandCollapse={handleExpandCollapse}
                onChangeContextModel={handlePaymentContextModelChange}
                onSaveContextToStorage={handleSaveContextToStorage}
            />
            <div className='flex row'>
                {paymentMethods?.paymentProducts && paymentMethods.paymentProducts.length > 0 && (
                    <ProductSelection
                        products={paymentMethods.paymentProducts}
                        onSelectedProduct={handleProductSelection}
                    />
                )}
                {paymentMethods && paymentMethods.accountsOnFile.length > 0 && (
                    <AccountOnFileSelection
                        accountsOnFile={paymentMethods.accountsOnFile}
                        onSelectedProduct={handleAccountOnFileSelection}
                    />
                )}
            </div>
            {errorMessage && <div className='error'>{errorMessage}</div>}
        </div>
    );
};

export default PaymentPage;

// examples/angular/src/app/pages/payment-page/payment-page.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { Component, ElementRef, inject, signal, ViewChild, WritableSignal } from '@angular/core';
import StorageService from '@shared/services/StorageService';
import { Router } from '@angular/router';
import {
  BasicPaymentProducts,
  CommunicationError,
  init,
  type OnlinePaymentSdk,
  SdkError,
} from 'onlinepayments-sdk-client-js';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { FormInput } from '../../components/form-elements/input/input';
import { LogoComponent } from '../../components/logo/logo';
import { FormSelect } from '../../components/form-elements/select/select';
import countries from '@shared/constants/countries';
import currencies from '@shared/constants/currencies';
import { ProductSelection } from '../../components/product-selection/product-selection';
import { AccountOnFileSelection } from '../../components/account-on-file-selection/account-on-file-selection';
import { Checkbox } from '../../components/form-elements/checkbox/checkbox';
import { LoaderService } from '../../services/loader-service';

type PaymentContextForm = {
  amountOfMoney: FormGroup<{
    amount: FormControl<string>;
    currencyCode: FormControl<string>;
  }>;
  countryCode: FormControl<string>;
  isRecurring: FormControl<boolean>;
};

@Component({
  selector: 'app-payment-page',
  imports: [
    FormInput,
    LogoComponent,
    FormSelect,
    ReactiveFormsModule,
    ProductSelection,
    AccountOnFileSelection,
    Checkbox,
  ],
  templateUrl: './payment-page.html',
  styleUrl: './payment-page.css',
  standalone: true,
})
export class PaymentPage {
  router = inject(Router);

  @ViewChild('paymentContextFormRef', { read: ElementRef })
  paymentContextFormRef!: ElementRef<HTMLFormElement>;

  sdk: OnlinePaymentSdk | null = null;

  paymentContext = new FormGroup<PaymentContextForm>({
    amountOfMoney: new FormGroup({
      amount: new FormControl('1000', { nonNullable: true }),
      currencyCode: new FormControl('EUR', { nonNullable: true }),
    }),
    countryCode: new FormControl('BE', { nonNullable: true }),
    isRecurring: new FormControl(false, { nonNullable: true }),
  });

  countryOptions = countries;
  currencyOptions = currencies;

  errorMessage = signal('');
  isFormExpanded = signal(true);
  paymentMethods: WritableSignal<BasicPaymentProducts | null> = signal(null);

  constructor(private loader: LoaderService) {}

  ngOnInit() {
    this.sdk = init(StorageService.getSessionData()!);
  }

  handleUnauthorizedError(error: SdkError) {
    if (error instanceof CommunicationError) {
      StorageService.clear();
      void this.router.navigate(['/']);
    }
  }

  getContext() {
    return {
      ...this.paymentContext.getRawValue(),
      amountOfMoney: {
        ...this.paymentContext.getRawValue().amountOfMoney,
        amount: Number(this.paymentContext.getRawValue().amountOfMoney.amount),
      },
    };
  }

  handleExpandCollapse() {
    this.isFormExpanded.update((prev) => !prev);
  }

  fetchPaymentProducts() {
    this.loader.show();
    this.sdk
      ?.getBasicPaymentProducts(this.getContext())
      .then((basicProducts) => {
        this.paymentMethods.set(basicProducts);
        this.errorMessage.set('');
        this.handleExpandCollapse();
      })
      .catch((error: SdkError) => {
        this.errorMessage.set(error?.message ?? '');
        this.handleUnauthorizedError(error);
        this.paymentMethods.set(null);
      })
      .finally(() => {
        this.loader.hide();
      });
  }

  handleSaveContext() {
    this.paymentContextFormRef.nativeElement.reportValidity();
    if (this.paymentContext.valid) {
      StorageService.setPaymentContext(this.getContext());
      void this.fetchPaymentProducts();
    }
  }

  async setSelectedProduct(productId: number) {
    this.loader.show();
    const paymentProduct = await this.sdk?.getPaymentProduct(productId, this.getContext());

    if (!paymentProduct) {
      this.errorMessage.set('Payment product not found.');
      return;
    }

    StorageService.setPaymentProductId(paymentProduct.id);
    this.loader.hide();

    return paymentProduct;
  }

  async handleProductChange(id: number) {
    const product = await this.setSelectedProduct(id);

    if (product?.paymentMethod === 'card') {
      void this.router.navigate(['/payment/credit-card']);
    } else if (product?.paymentMethod === 'mobile' && product?.label === 'GOOGLEPAY') {
      void this.router.navigate(['/payment/google-pay']);
    } else {
      this.errorMessage.set('This payment product is not supported in this demo.');
    }
  }

  async handleAccountOnFileChange(id: string) {
    const aof = this.paymentMethods()?.accountsOnFile.find((aof) => aof.id === id);
    if (aof) {
      const product = await this.setSelectedProduct(aof.paymentProductId);
      StorageService.setAccountOnFileId(id.toString());
      if (product?.paymentMethod === 'card') {
        void this.router.navigate(['/payment/account-on-file']);
      } else {
        this.errorMessage.set('This demo supports only card payment products.');
      }
    }
  }
}
