// examples/angular/src/app/components/form-elements/input/input.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  forwardRef,
  Input,
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { PaymentProduct } from 'onlinepayments-sdk-client-js';
import PaymentRequestUtility from '@shared/utilities/PaymentRequestUtility';

@Component({
  selector: 'wl-input',
  standalone: true,
  templateUrl: './input.html',
  styles: [':host { display: contents; }'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => FormInput),
      multi: true,
    },
  ],
})
export class FormInput implements ControlValueAccessor {
  @Input() label = '';
  @Input() placeholder = '';
  @Input() type: 'text' | 'url' | 'number' = 'text';
  @Input({ transform: booleanAttribute }) disabled = false;
  @Input() readonly = false;
  @Input({ transform: booleanAttribute }) required = false;
  @Input() id = '';
  @Input() ariaLabel = '';
  @Input() hint = '';
  @Input() autofocus = false;
  @Input() step = '1';

  @Input() classes = '';
  @Input() defaultValue = '';
  @Input() maskProduct?: PaymentProduct | null;
  @Input() maskField?: string;

  value = '';

  constructor(private cdr: ChangeDetectorRef) {}

  private onChange: (v: string) => void = () => {};
  private onTouch: () => void = () => {};

  private getInputMask(value: string): string {
    const request = PaymentRequestUtility.get(this.maskProduct!, this.maskField!, value);

    if (this.maskField) {
      return request?.getField(this.maskField).getMaskedValue() ?? value;
    }

    return value;
  }

  handleInput(e: Event) {
    const element = e.target as HTMLInputElement;
    const rawValue = element.value ?? '';

    const masked = this.maskField && this.maskProduct ? this.getInputMask(rawValue) : rawValue;

    if (masked !== rawValue) {
      element.value = masked;
    }

    this.value = masked;
    this.onChange(masked);
  }

  handleTouch(): void {
    this.onTouch();
    this.cdr.markForCheck();
  }

  writeValue(value: string | null): void {
    this.value = value ?? this.defaultValue ?? '';
    this.cdr.markForCheck();
  }

  registerOnChange(fn: (value: string) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouch = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
    this.cdr.markForCheck();
  }

  handleBlur(): void {
    this.onTouch();
  }

  protected readonly HTMLInputElement = HTMLInputElement;
}

// examples/vue/src/components/FormFields/Input/Input.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import type { Base, FieldAttributes } from '../types/base.ts';

type Props = Base & {
    modelValue?: string;
    type?: 'text' | 'url' | 'number';
    required?: boolean;
    disabled?: boolean;
    onChange?: (value: string) => void;
};

const props = withDefaults(defineProps<Props>(), {
    modelValue: '',
    type: 'text',
    required: false,
    disabled: false,
    fieldAttrs: () => ({}) as FieldAttributes
});

const emit = defineEmits<{
    (e: 'update:modelValue', value: string): void;
}>();

const handleInput = (e: Event) => {
    if (props.disabled) return;
    const value = (e.target as HTMLInputElement).value;
    emit('update:modelValue', value);
};
</script>

<template>
    <div :id="`${id}Field`" :class="['field', fieldAttrs?.className]">
        <label :for="id">{{ label }}</label>
        <input
            :type="type"
            :id="id"
            :name="id"
            :value="modelValue"
            :required="required"
            aria-autocomplete="none"
            aria-multiline="false"
            autocapitalize="off"
            autocorrect="off"
            data-enable-grammarly="false"
            data-gramm="false"
            spellcheck="false"
            :disabled="disabled"
            @input="handleInput"
            v-bind="fieldAttrs ?? {}"
        />
    </div>
</template>
