// examples/vue/src/pages/AccountOnFile/AccountOnFilePage.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import { computed, onMounted, reactive, ref, shallowRef } from 'vue';
import {
    type AccountOnFile,
    init,
    type OnlinePaymentSdk,
    type PaymentContextWithAmount,
    PaymentProduct
} from 'onlinepayments-sdk-client-js';
import { RouterLink, useRouter } from 'vue-router';
import RouterService from '../../services/RouterService.ts';
import StorageService from '@shared/services/StorageService';
import NumberFormatter from '@shared/utilities/NumberFormatter';
import PaymentRequestUtility from '@shared/utilities/PaymentRequestUtility';
import LoaderService from '../../services/LoaderService.ts';
import Input from '../../components/FormFields/Input/Input.vue';
import Logo from '../../components/Logo/Logo.vue';
import translations from '../../translations/translations.ts';
import PaymentProductService from '@shared/services/PaymentProductService.ts';

const router = useRouter();
const { redirectToPage } = RouterService(router);

const cvv = ref('');

const sdk = shallowRef<OnlinePaymentSdk>();
const paymentContext = shallowRef<PaymentContextWithAmount>();
const paymentProduct = shallowRef<PaymentProduct | null>(null);
const accountOnFile = ref<AccountOnFile>();

const dirtyFields = reactive({
    cvv: false
});

const errors = computed(() => ({
    cvv: dirtyFields.cvv ? handleValidateField('cvv', cvv.value) : false
}));

const sessionDetails = StorageService.getSessionData();
const context = StorageService.getPaymentContext();
const productId = StorageService.getPaymentProductId();
const accountOnFileId = StorageService.getAccountOnFileId();

const isLoading = ref(true);

const initData = async () => {
    LoaderService.show();
    if (sessionDetails) {
        sdk.value = init(sessionDetails);
    }

    if (context) {
        paymentContext.value = context;
    }

    if (productId) {
        paymentProduct.value = await PaymentProductService.getPaymentProduct(
            sdk.value!,
            productId,
            paymentContext.value!
        );
    }

    if (!paymentProduct.value) {
        redirectToPage('/payment');
    }

    if (accountOnFileId) {
        if (paymentProduct.value) {
            accountOnFile.value = paymentProduct?.value?.accountsOnFile.find(
                (aof) => aof.paymentProductId === paymentProduct.value?.id
            );
        }
    }

    isLoading.value = false;
    LoaderService.hide();
};

onMounted(() => {
    initData().catch((error) => console.log(error));
});

const handleValidateField = (key: string, value: string) => {
    const paymentRequest = PaymentRequestUtility.get(paymentProduct.value, key, value);

    return !paymentRequest?.getField(key).validate().isValid;
};

const getCvvMaskedValue = () => {
    const request = PaymentRequestUtility.get(paymentProduct.value, 'cvv', cvv.value);
    cvv.value = request?.getField('cvv').getMaskedValue() ?? cvv.value ?? '';
    dirtyFields['cvv'] = true;
};

const getExpiryDateMaskedValue = () => {
    const paymentRequest = PaymentRequestUtility.get(
        paymentProduct.value,
        'expiryDate',
        accountOnFile?.value?.getValue('expiryDate')
    );

    return (
        paymentRequest?.getField('expiryDate').getMaskedValue() ?? accountOnFile?.value?.getValue('expiryDate') ?? ''
    );
};

const handleSubmit = () => {
    const paymentRequest = PaymentRequestUtility.get(paymentProduct.value);

    if (cvv.value && paymentProduct?.value?.id) {
        paymentRequest?.setValue('cvv', cvv.value);
    }

    paymentRequest?.setAccountOnFile(accountOnFile.value!);

    if (paymentRequest?.validate().isValid && accountOnFile.value?.id && cvv.value && paymentProduct?.value?.id) {
        StorageService.setPaymentRequest(paymentRequest);

        StorageService.setCardPaymentSpecificData({
            token: accountOnFile.value.id,
            cvv: cvv.value,
            paymentProductId: paymentProduct.value.id
        });

        redirectToPage('/payment/finalize');
    }
};
</script>

<template>
    <div class="page flex column center">
        <Logo />
        <h1 class="m-0">{{ translations.pay_with_a_credit_card }}</h1>
        <p class="self-start m-0">
            <strong
                >Total amount:
                {{
                    paymentContext?.amountOfMoney?.currencyCode &&
                    paymentContext?.amountOfMoney.amount &&
                    NumberFormatter.formatAmount(
                        paymentContext?.amountOfMoney.currencyCode,
                        paymentContext?.amountOfMoney.amount
                    )
                }}
                {{ paymentContext?.amountOfMoney.currencyCode }}</strong
            >
        </p>
        <p class="self-start m-0">{{ translations.selected_card_type }} {{ paymentProduct?.label }}</p>
        <RouterLink to="/payment" class="button link self-start">
            {{ translations.back_to_payment_method_selection }}
        </RouterLink>
        <form :class="{ form: true, 'form-max-height': true, invisible: isLoading }" @submit.prevent="handleSubmit">
            <Input
                id="card-number"
                :label="translations.card_number"
                required
                disabled
                :model-value="accountOnFile?.label"
            />
            <div class="flex row">
                <Input
                    id="expiry-date"
                    :label="translations.expiry_date"
                    required
                    disabled
                    :model-value="getExpiryDateMaskedValue()"
                />
                <Input
                    v-if="paymentProduct?.fields.find((field) => field.id === 'cvv')"
                    id="cvv"
                    :label="translations.security_code"
                    required
                    type="number"
                    v-model="cvv"
                    @update:model-value="() => getCvvMaskedValue()"
                    :fieldAttrs="{ className: errors.cvv ? 'error' : '' }"
                />
            </div>
            <Input
                id="cardholder-name"
                :label="translations.cardholder_name"
                required
                disabled
                :model-value="accountOnFile?.getValue('cardholderName')"
            />
            <button class="button primary" type="submit">{{ translations.pay_now }}</button>
        </form>
    </div>
</template>

// examples/react/src/pages/AccountOnFile/AccountOnFilePage.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { type FormEvent, useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useLoader } from '../../components/Loader/Loader.tsx';
import {
    type AccountOnFile,
    init,
    type OnlinePaymentSdk,
    type PaymentContextWithAmount,
    PaymentProduct,
    type SessionData
} from 'onlinepayments-sdk-client-js';
import StorageService from '@shared/services/StorageService';
import NumberFormatter from '@shared/utilities/NumberFormatter';
import Logo from '../../components/Logo/Logo.tsx';
import Input from '../../components/FormFields/Input/Input.tsx';
import translations from '../../translations/translations.ts';
import PaymentRequestUtility from '@shared/utilities/PaymentRequestUtility';
import PaymentProductService from '@shared/services/PaymentProductService.ts';

const AccountOnFilePage = () => {
    const navigate = useNavigate();
    const sdk = useRef<OnlinePaymentSdk>(null);

    const { show, hide } = useLoader();

    const [paymentContext, setPaymentContext] = useState<PaymentContextWithAmount>();
    const [paymentProduct, setPaymentProduct] = useState<PaymentProduct>();

    const [accountOnFile, setAccountOnFile] = useState<AccountOnFile>();
    const [cvv, setCvv] = useState<string>();
    const [error, setError] = useState(false);

    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const initData = async () => {
            show();

            const sessionData = StorageService.getSessionData();
            const paymentContext = StorageService.getPaymentContext();

            if (!sessionData || !paymentContext) {
                hide();
                navigate('/');
                return;
            }

            sdk.current = init(sessionData);
            setPaymentContext(paymentContext);

            const accountOnFileId = StorageService.getAccountOnFileId();
            const paymentProductId = StorageService.getPaymentProductId();

            if (!accountOnFileId || !paymentProductId) {
                hide();
                navigate('/payment');
                return;
            }

            sdk.current = init(sessionData as SessionData);

            const product = await PaymentProductService.getPaymentProduct(
                sdk.current,
                Number(paymentProductId),
                paymentContext
            );

            if (!product) {
                hide();
                navigate('/payment');
                return;
            }

            setPaymentProduct(product);
            hide();
        };

        initData().catch((error) => console.error(error));
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
        if (!paymentProduct) {
            return;
        }

        setIsLoading(false);

        const accountOnFileId = StorageService.getAccountOnFileId();
        if (accountOnFileId) {
            setAccountOnFile(paymentProduct.accountsOnFile.find((aof) => aof.id === accountOnFileId));
        }
    }, [paymentProduct]);

    const handleChangeCvv = (value: string, key: string) => {
        const paymentRequest = PaymentRequestUtility.get(paymentProduct, key, value);

        const maskedCvv = paymentRequest?.getField(key).getMaskedValue();
        if (!paymentRequest?.getField(key).validate().isValid) {
            setError(true);
        } else {
            setError(false);
        }

        setCvv(maskedCvv);
    };

    const getExpiryDateMaskedValue = () => {
        const paymentRequest = PaymentRequestUtility.get(
            paymentProduct,
            'expiryDate',
            accountOnFile?.getValue('expiryDate')
        );

        return paymentRequest?.getField('expiryDate').getMaskedValue() ?? '';
    };

    const handleProcessPayment = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        const paymentRequest = PaymentRequestUtility.get(paymentProduct, 'cvv', cvv)!;
        if (accountOnFile) {
            paymentRequest.setAccountOnFile(accountOnFile);
        }

        if (paymentRequest.validate().isValid && accountOnFile && cvv && paymentProduct?.id) {
            StorageService.setPaymentRequest(paymentRequest);

            StorageService.setCardPaymentSpecificData({
                token: accountOnFile.id,
                cvv: cvv,
                paymentProductId: paymentProduct.id
            });

            navigate('/payment/finalize');
        }
    };

    return (
        <div className='page flex column center'>
            <Logo />
            <h1 className='m-0'>{translations.pay_with_a_credit_card}</h1>
            <p className='self-start m-0'>
                <strong>
                    {translations.total_amount}{' '}
                    {paymentContext &&
                        paymentContext.amountOfMoney.currencyCode &&
                        paymentContext.amountOfMoney.currencyCode &&
                        NumberFormatter.formatAmount(
                            paymentContext.amountOfMoney.currencyCode,
                            paymentContext.amountOfMoney.amount
                        )}{' '}
                    {paymentContext?.amountOfMoney?.currencyCode}
                </strong>
            </p>
            <p className='self-start m-0'>
                {translations.selected_card_type} {paymentProduct?.label}
            </p>
            <Link to='/payment' className='button link self-start'>
                {translations.back_to_payment_method_selection}
            </Link>
            <form className={`form form-max-height ${!isLoading ? '' : 'invisible'}`} onSubmit={handleProcessPayment}>
                <Input
                    id='cardNumber'
                    type='text'
                    label={translations.card_number}
                    value={accountOnFile?.label ?? ''}
                    disabled={true}
                    required={true}
                />
                <div className='flex row'>
                    <Input
                        id='expiryDate'
                        type='text'
                        label={translations.expiry_date}
                        value={accountOnFile ? getExpiryDateMaskedValue() : ''}
                        disabled={true}
                        required={true}
                    />
                    {paymentProduct?.fields.find((field) => field.id === 'cvv') && (
                        <Input
                            id='cvv'
                            value={cvv}
                            onChange={(value) => handleChangeCvv(value, 'cvv')}
                            label={translations.security_code}
                            type='number'
                            required={true}
                            fieldAttrs={{ step: '1', className: error ? 'error' : '' }}
                        />
                    )}
                </div>
                <Input
                    id='cardholderName'
                    type='text'
                    label={translations.cardholder_name}
                    value={accountOnFile?.getValue('cardholderName') ?? ''}
                    disabled={true}
                    required={true}
                />
                <button className='button primary' type='submit'>
                    {translations.pay_now}
                </button>
            </form>
        </div>
    );
};

export default AccountOnFilePage;
