// examples/angular/src/app/pages/account-on-file-page/account-on-file-page.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { Component, effect, ElementRef, inject, signal, ViewChild } from '@angular/core';
import {
  AccountOnFile,
  init,
  OnlinePaymentSdk,
  PaymentContextWithAmount,
  PaymentProduct,
} from 'onlinepayments-sdk-client-js';
import StorageService from '@shared/services/StorageService';
import PaymentRequestUtility from '@shared/utilities/PaymentRequestUtility';
import { Router, RouterLink } from '@angular/router';
import { FormControl, FormGroup, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { FormInput } from '../../components/form-elements/input/input';
import { LogoComponent } from '../../components/logo/logo';
import NumberFormatter from '@shared/utilities/NumberFormatter';
import { PaymentValidation } from '../../utilities/payment-validation';
import PaymentProductService from '@shared/services/PaymentProductService';
import { LoaderService } from '../../services/loader-service';

type AccountOnFilePaymentForm = {
  cardNumber: FormControl<string>;
  cvv: FormControl<string>;
  expiryDate: FormControl<string>;
  cardholderName: FormControl<string>;
};

@Component({
  selector: 'app-account-on-file-selection-page',
  imports: [FormInput, FormsModule, LogoComponent, ReactiveFormsModule, RouterLink],
  templateUrl: './account-on-file-page.html',
  standalone: true,
})
export class AccountOnFilePage {
  router = inject(Router);

  @ViewChild('accountOnFileFormRef', { read: ElementRef })
  accountOnFileFormRef!: ElementRef<HTMLFormElement>;

  sdk: OnlinePaymentSdk | null = null;
  accountOnFile = signal<AccountOnFile | undefined>(undefined);
  paymentProduct: PaymentProduct | null = null;

  paymentContext: PaymentContextWithAmount | null = StorageService.getPaymentContext();

  isLoading: boolean = true;

  form = new FormGroup<AccountOnFilePaymentForm>({
    cvv: new FormControl('', { nonNullable: true }),
    cardholderName: new FormControl({ value: '', disabled: true }, { nonNullable: true }),
    expiryDate: new FormControl({ value: '', disabled: true }, { nonNullable: true }),
    cardNumber: new FormControl({ value: '', disabled: true }, { nonNullable: true }),
  });

  setupValidators() {
    const fields = ['cvv'] as const;
    PaymentValidation.applyValidators(this.form, this.paymentProduct, fields);
  }

  constructor(private loader: LoaderService) {
    effect(() => {
      this.form.patchValue({
        cardNumber: this.getCardNumber(),
        cardholderName: this.getCardholderName(),
        expiryDate: this.getExpiryDate(),
      });
    });
  }

  async initData(): Promise<void> {
    this.loader.show();
    this.sdk = init(StorageService.getSessionData()!);

    this.paymentProduct = await PaymentProductService.getPaymentProduct(
      this.sdk,
      Number(StorageService.getPaymentProductId()!),
      StorageService.getPaymentContext()!,
    );

    if (!this.paymentProduct) {
      void this.router.navigate(['/payment']);
      return;
    }

    const aofId = StorageService.getAccountOnFileId();
    this.accountOnFile.set(this.paymentProduct?.accountsOnFile.find((aof) => aof.id === aofId));

    this.setupValidators();

    this.isLoading = false;
    this.loader.hide();
  }

  ngOnInit() {
    this.initData().catch((error) => console.log(error));
  }

  ngOnDestroy() {
    StorageService.clearItem('accountOnFileId');
  }

  handleProcessPayment() {
    this.accountOnFileFormRef.nativeElement.reportValidity();

    const paymentRequest = PaymentRequestUtility.get(
      this.paymentProduct ?? undefined,
      'cvv',
      this.form.getRawValue().cvv,
    )!;

    this.accountOnFile() && paymentRequest.setAccountOnFile(this.accountOnFile());

    if (paymentRequest.validate().isValid && !!this.form.get('cvv')) {
      StorageService.setPaymentRequest(paymentRequest);

      StorageService.setCardPaymentSpecificData({
        token: this.accountOnFile()!.id,
        cvv: this.form.getRawValue().cvv!,
        paymentProductId: this.paymentProduct!.id,
      });

      void this.router.navigate(['payment/finalize']);
    }
  }

  getCardNumber() {
    return this.accountOnFile()?.label ?? '';
  }

  getCardholderName() {
    return this.accountOnFile()?.getValue('cardholderName') ?? '';
  }

  getExpiryDate() {
    const paymentRequest = PaymentRequestUtility.get(
      this.paymentProduct ?? undefined,
      'expiryDate',
      this.accountOnFile()?.getValue('expiryDate'),
    );

    return paymentRequest?.getField('expiryDate').getMaskedValue() ?? '';
  }

  getFormattedAmount() {
    return NumberFormatter.formatAmount(
      this.paymentContext?.amountOfMoney.currencyCode ?? 'EUR',
      this.paymentContext?.amountOfMoney.amount ?? 1000,
    );
  }

  getCurrency() {
    return this.paymentContext?.amountOfMoney.currencyCode;
  }

  hasField(id: string): boolean {
    return !!this.paymentProduct?.getField(id);
  }
}

// examples/react/src/pages/AccountOnFile/AccountOnFilePage.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { type FormEvent, useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useLoader } from '../../components/Loader/Loader.tsx';
import {
    type AccountOnFile,
    init,
    type OnlinePaymentSdk,
    type PaymentContextWithAmount,
    PaymentProduct,
    type SessionData
} from 'onlinepayments-sdk-client-js';
import StorageService from '@shared/services/StorageService';
import NumberFormatter from '@shared/utilities/NumberFormatter';
import Logo from '../../components/Logo/Logo.tsx';
import Input from '../../components/FormFields/Input/Input.tsx';
import translations from '../../translations/translations.ts';
import PaymentRequestUtility from '@shared/utilities/PaymentRequestUtility';
import PaymentProductService from '@shared/services/PaymentProductService.ts';

const AccountOnFilePage = () => {
    const navigate = useNavigate();
    const sdk = useRef<OnlinePaymentSdk>(null);

    const { show, hide } = useLoader();

    const [paymentContext, setPaymentContext] = useState<PaymentContextWithAmount>();
    const [paymentProduct, setPaymentProduct] = useState<PaymentProduct>();

    const [accountOnFile, setAccountOnFile] = useState<AccountOnFile>();
    const [cvv, setCvv] = useState<string>();
    const [error, setError] = useState(false);

    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const initData = async () => {
            show();

            const sessionData = StorageService.getSessionData();
            const paymentContext = StorageService.getPaymentContext();

            if (!sessionData || !paymentContext) {
                hide();
                navigate('/');
                return;
            }

            sdk.current = init(sessionData);
            setPaymentContext(paymentContext);

            const accountOnFileId = StorageService.getAccountOnFileId();
            const paymentProductId = StorageService.getPaymentProductId();

            if (!accountOnFileId || !paymentProductId) {
                hide();
                navigate('/payment');
                return;
            }

            sdk.current = init(sessionData as SessionData);

            const product = await PaymentProductService.getPaymentProduct(
                sdk.current,
                Number(paymentProductId),
                paymentContext
            );

            if (!product) {
                hide();
                navigate('/payment');
                return;
            }

            setPaymentProduct(product);
            hide();
        };

        initData().catch((error) => console.error(error));
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
        if (!paymentProduct) {
            return;
        }

        setIsLoading(false);

        const accountOnFileId = StorageService.getAccountOnFileId();
        if (accountOnFileId) {
            setAccountOnFile(paymentProduct.accountsOnFile.find((aof) => aof.id === accountOnFileId));
        }
    }, [paymentProduct]);

    const handleChangeCvv = (value: string, key: string) => {
        const paymentRequest = PaymentRequestUtility.get(paymentProduct, key, value);

        const maskedCvv = paymentRequest?.getField(key).getMaskedValue();
        if (!paymentRequest?.getField(key).validate().isValid) {
            setError(true);
        } else {
            setError(false);
        }

        setCvv(maskedCvv);
    };

    const getExpiryDateMaskedValue = () => {
        const paymentRequest = PaymentRequestUtility.get(
            paymentProduct,
            'expiryDate',
            accountOnFile?.getValue('expiryDate')
        );

        return paymentRequest?.getField('expiryDate').getMaskedValue() ?? '';
    };

    const handleProcessPayment = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        const paymentRequest = PaymentRequestUtility.get(paymentProduct, 'cvv', cvv)!;
        if (accountOnFile) {
            paymentRequest.setAccountOnFile(accountOnFile);
        }

        if (paymentRequest.validate().isValid && accountOnFile && cvv && paymentProduct?.id) {
            StorageService.setPaymentRequest(paymentRequest);

            StorageService.setCardPaymentSpecificData({
                token: accountOnFile.id,
                cvv: cvv,
                paymentProductId: paymentProduct.id
            });

            navigate('/payment/finalize');
        }
    };

    return (
        <div className='page flex column center'>
            <Logo />
            <h1 className='m-0'>{translations.pay_with_a_credit_card}</h1>
            <p className='self-start m-0'>
                <strong>
                    {translations.total_amount}{' '}
                    {paymentContext &&
                        paymentContext.amountOfMoney.currencyCode &&
                        paymentContext.amountOfMoney.currencyCode &&
                        NumberFormatter.formatAmount(
                            paymentContext.amountOfMoney.currencyCode,
                            paymentContext.amountOfMoney.amount
                        )}{' '}
                    {paymentContext?.amountOfMoney?.currencyCode}
                </strong>
            </p>
            <p className='self-start m-0'>
                {translations.selected_card_type} {paymentProduct?.label}
            </p>
            <Link to='/payment' className='button link self-start'>
                {translations.back_to_payment_method_selection}
            </Link>
            <form className={`form form-max-height ${!isLoading ? '' : 'invisible'}`} onSubmit={handleProcessPayment}>
                <Input
                    id='cardNumber'
                    type='text'
                    label={translations.card_number}
                    value={accountOnFile?.label ?? ''}
                    disabled={true}
                    required={true}
                />
                <div className='flex row'>
                    <Input
                        id='expiryDate'
                        type='text'
                        label={translations.expiry_date}
                        value={accountOnFile ? getExpiryDateMaskedValue() : ''}
                        disabled={true}
                        required={true}
                    />
                    {paymentProduct?.fields.find((field) => field.id === 'cvv') && (
                        <Input
                            id='cvv'
                            value={cvv}
                            onChange={(value) => handleChangeCvv(value, 'cvv')}
                            label={translations.security_code}
                            type='number'
                            required={true}
                            fieldAttrs={{ step: '1', className: error ? 'error' : '' }}
                        />
                    )}
                </div>
                <Input
                    id='cardholderName'
                    type='text'
                    label={translations.cardholder_name}
                    value={accountOnFile?.getValue('cardholderName') ?? ''}
                    disabled={true}
                    required={true}
                />
                <button className='button primary' type='submit'>
                    {translations.pay_now}
                </button>
            </form>
        </div>
    );
};

export default AccountOnFilePage;
