// examples/vue/src/components/Header/Header.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import ThemeSwitcher from '../ThemeSwitcher/ThemeSwitcher.vue';
</script>

<template>
    <header class="main-header small">
        <RouterLink class="button link" to="/">Home</RouterLink>
        <ThemeSwitcher />
    </header>
</template>

// examples/svelte/src/components/Header/Header.svelte
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script lang="ts">
    import ThemeSwitcher from '../ThemeSwitcher/ThemeSwitcher.svelte';
</script>

<header class="main-header small">
    <a class="button link" href="/">Home</a>
    <ThemeSwitcher />
</header>
