// examples/vue/src/App.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import Header from './components/Header/Header.vue';
import Loader from './components/Loader/Loader.vue';
</script>

<template>
    <Header />
    <div id="app" class="flex">
        <RouterView />
        <Loader />
    </div>
</template>

// examples/angular/src/app/app.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { Component, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { LoaderProvider } from './components/loader-provider/loader-provider';

@Component({
  selector: 'app-root',
  templateUrl: './app.html',
  standalone: true,
  imports: [RouterOutlet, LoaderProvider],
})
export class App {
  protected readonly title = signal('angular');
}
