// examples/angular/src/app/components/form-elements/select/select.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  forwardRef,
  Input,
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

export type Base = {
  id: string;
  label?: string;
  disabled?: boolean;
  classes?: string;
};

export type Option = { label: string; value: string };

type Props = Base & {
  required?: boolean;
  options: Option[];
};

@Component({
  selector: 'wl-select',
  standalone: true,
  imports: [],
  templateUrl: './select.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => FormSelect),
      multi: true,
    },
  ],
})
export class FormSelect implements ControlValueAccessor {
  @Input() label!: Props['label'];
  @Input() id!: Props['id'];
  @Input() options: Props['options'] = [];
  @Input() disabled: Props['disabled'] = false;
  @Input() classes: Base['classes'] = '';

  @Input({ transform: booleanAttribute }) required = false;

  value: string = '';

  private onChange: (val: string) => void = () => {};
  private onTouched: () => void = () => {};

  constructor(private cdr: ChangeDetectorRef) {}

  writeValue(val: string | null): void {
    this.value = val ?? '';
    this.cdr.markForCheck();
  }

  registerOnChange(fn: (val: string) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
    this.cdr.markForCheck();
  }

  handleChange(event: Event): void {
    const next = (event.target as HTMLSelectElement).value;
    this.value = next;
    this.onChange(next);
  }

  handleBlur(): void {
    this.onTouched();
  }
}

// examples/svelte/src/components/FormFields/Select/Select.svelte
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script lang="ts">
    import type { Base } from '../types';

    export type Option = {
        label: string;
        value: string;
    };

    export let id: string;
    export let label: string;
    export let options: Option[] = [];
    export let value: string | undefined = '';
    export let required: boolean = false;
    export let disabled: boolean = false;
    export let fieldAttrs: Base['fieldAttrs'] = {};
    export let onChange: ((value: string) => void) | undefined = undefined;

    const handleChange = (event: Event) => {
        const target = event.target as HTMLSelectElement;
        onChange?.(target.value);
    };
</script>

<div class={`field ${fieldAttrs?.className || ''}`} id={`${id}Field`}>
    <label for={id}>{label}</label>
    <select
        id={id}
        name={id}
        required={required}
        disabled={disabled}
        bind:value={value}
        on:change={handleChange}
        {...fieldAttrs}
    >
        {#each options as option (option.value)}
            <option value={option.value}>{option.label}</option>
        {/each}
    </select>
</div>
