// examples/svelte/src/components/PaymentDetails/PaymentDetails.svelte
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script lang="ts">
    import Input from '../FormFields/Input/Input.svelte';
    import Select from '../FormFields/Select/Select.svelte';
    import Checkbox from '../FormFields/Checkbox/Checkbox.svelte';
    import type { PaymentContextWithAmount } from 'onlinepayments-sdk-client-js';
    import countries from '@shared/constants/countries';
    import currencies from '@shared/constants/currencies';
    import { translations } from '../../translations/translations';
    import type DeepPartial from '@shared/types/DeepPartial';

    export let paymentContext: DeepPartial<PaymentContextWithAmount> | undefined = {};
    export let isFormExpanded: boolean = true;
    export let onExpandCollapse: () => void;
    /**
     * Callback fired when the context is valid and should be persisted.
     * @param context - The current payment context.
     */
    export let onSaveContextToStorage: (context: PaymentContextWithAmount) => void;

    /**
     * Handles form submission: prevents default behavior,
     * triggers expand/collapse, and persists the context if valid.
     */
    const handleSubmit = (e: Event) => {
        e.preventDefault();
        onExpandCollapse?.();

        if (
            paymentContext?.countryCode &&
            paymentContext?.amountOfMoney?.currencyCode &&
            paymentContext?.amountOfMoney?.amount != null
        ) {
            onSaveContextToStorage?.({ ...paymentContext } as PaymentContextWithAmount);
        }
    };

    const handleInput = (e:Event) => {
        const val = (e.target as HTMLInputElement)?.value;
        if (paymentContext && paymentContext.amountOfMoney) {
            paymentContext.amountOfMoney.amount = val ? Number(val) : 0;
        }
    }
</script>

<div>
    <p class='text-left'>Order details:</p>
    <button
        class="button expand-button {isFormExpanded ? '' : 'show'}"
        class:show={!isFormExpanded}
        type="button"
        id='paymentDetailsFormExpandButton'
        on:click={onExpandCollapse}
    >
        {translations.expand}
    </button>

    <form
        class="form"
        class:collapse={!isFormExpanded}
        id="paymentDetailsForm"
        on:submit={handleSubmit}
    >
        <Input
            id="amount"
            label={translations.amount_in_the_smallest_denominator}
            type="number"
            required
            value={paymentContext?.amountOfMoney?.amount?.toString() ?? ''}
            on:input={handleInput}
            fieldAttrs={{ step: '1' }}
        />

        <Select
            id="countryCode"
            label={translations.country}
            required
            options={countries}
            bind:value={paymentContext!.countryCode}
        />

        <Select
            id="currency"
            label={translations.currency}
            required
            options={currencies}
            bind:value={paymentContext!.amountOfMoney!.currencyCode}
        />

        <Checkbox
            id="isRecurring"
            label={translations.is_recurring_payment}
            bind:checked={paymentContext!.isRecurring!}
        />

        <button class="button primary" type="submit">
            {translations.get_payment_methods}
        </button>

        <div class="errorMessage" id="paymentDetailsErrorMessage"></div>
    </form>
</div>

<style>
    #paymentDetailsFormExpandButton {
        display: none;
        width: 75px;
        align-self: flex-end;
    }

    #paymentDetailsFormExpandButton.show {
        display: block;
    }

    #paymentDetailsForm {
        overflow: hidden;
        max-height: 600px;
        transition: all 0.2s linear;
    }

    #paymentDetailsForm.collapse {
        max-height: 0;
        padding: 0;
    }
</style>

// examples/react/src/components/PaymentDetails/PaymentDetails.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { type FormEvent, memo } from 'react';
import './index.css';
import type { AmountOfMoney, PaymentContext, PaymentContextWithAmount } from 'onlinepayments-sdk-client-js';
import Input from '../FormFields/Input/Input.tsx';
import Select from '../FormFields/Select/Select.tsx';
import Checkbox from '../FormFields/Checkbox/Checkbox.tsx';
import countries from '@shared/constants/countries';
import currencies from '@shared/constants/currencies';
import translations from '../../translations/translations.ts';

type Props = {
    paymentContext?: PaymentContext;
    isFormExpanded?: boolean;
    onExpandCollapse?: () => void;
    onChangeContextModel?: <K extends keyof PaymentContextWithAmount>(value: PaymentContext[K], prop: K) => void;
    onSaveContextToStorage?: (paymentContext: PaymentContextWithAmount) => void;
};

const PaymentDetails = ({
    paymentContext,
    isFormExpanded,
    onExpandCollapse,
    onChangeContextModel,
    onSaveContextToStorage
}: Props) => {
    const handleSaveContextToStorage = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        onExpandCollapse?.();

        if (
            paymentContext?.countryCode &&
            paymentContext?.amountOfMoney?.currencyCode &&
            paymentContext?.amountOfMoney?.amount
        ) {
            const newPaymentContext: PaymentContextWithAmount = {
                ...(paymentContext as PaymentContext),
                amountOfMoney: { ...paymentContext.amountOfMoney, amount: paymentContext.amountOfMoney.amount }
            };

            onSaveContextToStorage?.(newPaymentContext);
        }
    };

    return (
        <div>
            <p className='text-left'></p>
            <button
                className={`button expand-button ${isFormExpanded ? '' : 'show'}`}
                type='button'
                id='paymentDetailsFormExpandButton'
                onClick={onExpandCollapse}
            >
                {translations.expand}
            </button>
            <form
                className={`form ${isFormExpanded ? '' : 'collapse'}`}
                id='paymentDetailsForm'
                onSubmit={handleSaveContextToStorage}
            >
                <Input
                    label={translations.amount_in_the_smallest_denominator}
                    id='amount'
                    type='number'
                    onChange={(value) =>
                        onChangeContextModel?.(
                            {
                                ...paymentContext?.amountOfMoney,
                                amount: value ? Number(value) : undefined
                            } as AmountOfMoney,
                            'amountOfMoney'
                        )
                    }
                    required={true}
                    fieldAttrs={{ step: '1' }}
                    value={paymentContext?.amountOfMoney?.amount?.toString()}
                />
                <Select
                    label={translations.country}
                    id='countryCode'
                    options={countries}
                    required={true}
                    value={paymentContext?.countryCode}
                    onChange={(value) => onChangeContextModel?.(value, 'countryCode')}
                />
                <Select
                    label={translations.currency}
                    id='currency'
                    options={currencies}
                    required={true}
                    value={paymentContext?.amountOfMoney?.currencyCode}
                    onChange={(value) =>
                        onChangeContextModel?.(
                            {
                                ...paymentContext?.amountOfMoney,
                                currencyCode: value
                            } as AmountOfMoney,
                            'amountOfMoney'
                        )
                    }
                />
                <Checkbox
                    label={translations.is_recurring_payment}
                    id='isRecurring'
                    onChange={(value) => onChangeContextModel?.(value, 'isRecurring')}
                    checked={paymentContext?.isRecurring}
                />
                <button className='button primary' type='submit'>
                    {translations.get_payment_methods}
                </button>
                <div className='errorMessage' id='paymentDetailsErrorMessage'></div>
            </form>
        </div>
    );
};

export default memo(PaymentDetails);
