// examples/vue/src/pages/Session/SessionPage.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import translations from '../../translations/translations.ts';
import { mockApiUrl, useMockApi } from '../../config.ts';
import Logo from '../../components/Logo/Logo.vue';
import Input from '../../components/FormFields/Input/Input.vue';
import { type ErrorResponse, type SessionData } from 'onlinepayments-sdk-client-js';
import StorageService from '@shared/services/StorageService';
import ApiService from '@shared/services/ApiService';
import { useRouter } from 'vue-router';
import RouterService from '../../services/RouterService.ts';
import LoaderService from '../../services/LoaderService.ts';

const router = useRouter();
const { redirectToPage } = RouterService(router);

const SessionDetailsInitialData = {
    clientSessionId: '',
    assetUrl: '',
    customerId: '',
    clientApiUrl: ''
} satisfies SessionData;

const sessionDetailsModel: SessionData = reactive({ ...SessionDetailsInitialData });

const errorMessage = ref('');

onMounted(() => {
    const sessionDetails = StorageService.getSessionData();

    if (sessionDetails) {
        Object.assign(sessionDetailsModel, sessionDetails);
    }
});

const handleSubmit = () => {
    if (
        !sessionDetailsModel?.assetUrl ||
        !sessionDetailsModel.clientApiUrl ||
        !sessionDetailsModel.clientSessionId ||
        !sessionDetailsModel.customerId
    ) {
        errorMessage.value = translations.please_fill_in_all_the_data;
    } else {
        StorageService.clear();
        StorageService.setSession(sessionDetailsModel);

        redirectToPage('/payment');
    }
};

const fetchSessionFromAPI = async () => {
    LoaderService.show();
    let message = '';

    ApiService(mockApiUrl)
        .getSession()
        .then((response) => {
            Object.assign(sessionDetailsModel, response);
        })
        .catch((error: ErrorResponse) => {
            if (error.errors?.length) {
                message = translations.errors_while_fetching_data + error.errors.map((err) => err.message).join(', ');
            } else {
                message = translations.there_was_an_error_fetching_data_did_you_mock_api;
            }
        })
        .finally(() => {
            errorMessage.value = message;
            LoaderService.hide();
        });
};

const pasteData = () => {
    let error = '';

    navigator.clipboard.readText().then((text) => {
        try {
            const data = JSON.parse(text);
            if (data?.assetUrl && data.clientApiUrl && data.clientSessionId && data.customerId) {
                Object.assign(sessionDetailsModel, {
                    assetUrl: data.assetUrl,
                    clientApiUrl: data.clientApiUrl,
                    clientSessionId: data.clientSessionId,
                    customerId: data.customerId
                });
                return;
            }
        } catch {
            error = translations.the_clipboard_does_not_contain_valid_data;
        }
    });
    errorMessage.value = error;
};
</script>

<template>
    <div class="page">
        <Logo />
        <h1>{{ translations.initialize_session }}</h1>
        <p>
            {{
                translations.to_process_the_payment_using_services_provided_by_the_online_payments_platform +
                translations.information_must_be_provided_as_a_merchant
            }}
        </p>
        <div class="flex column mt-1">
            <form class="form" id="sessionForm" @submit.prevent="handleSubmit">
                <Input
                    id="asset-url"
                    :label="translations.asset_url"
                    required
                    v-model="sessionDetailsModel.assetUrl"
                    type="url"
                />
                <Input
                    id="client-api-url"
                    :label="translations.client_api_url"
                    required
                    v-model="sessionDetailsModel.clientApiUrl"
                    type="url"
                />
                <Input
                    id="client-session-id"
                    :label="translations.client_session_id"
                    required
                    v-model="sessionDetailsModel.clientSessionId"
                />
                <Input id="customer-id" label="Customer ID" required v-model="sessionDetailsModel.customerId" />
                <button class="button primary" type="submit">{{ translations.start_session }}</button>
            </form>
            <div class="label">{{ translations.get_session_details_from }}</div>
            <div class="flex row center">
                <button class="button" type="button" @click="pasteData">{{ translations.clipboard }}</button>
                <button v-if="useMockApi" class="button" type="button" @click="fetchSessionFromAPI">
                    {{ translations.mock_api }}
                </button>
            </div>
        </div>
        <div class="error mt-1" id="errorMessage">{{ errorMessage }}</div>
    </div>
</template>

// examples/react/src/pages/Session/SessionPage.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { type FormEvent, useEffect, useState } from 'react';
import { type ErrorResponse, type SessionData } from 'onlinepayments-sdk-client-js';
import { useNavigate } from 'react-router-dom';
import { mockApiUrl, useMockApi } from '../../config.ts';
import { useLoader } from '../../components/Loader/Loader.tsx';
import ApiService from '@shared/services/ApiService';
import StorageService from '@shared/services/StorageService';
import Logo from '../../components/Logo/Logo.tsx';
import Input from '../../components/FormFields/Input/Input.tsx';
import translations from '../../translations/translations.ts';

const SessionInitialState = {
    clientSessionId: '',
    clientApiUrl: '',
    customerId: '',
    assetUrl: ''
} satisfies Partial<SessionData>;

const SessionPage = () => {
    const apiService = ApiService(mockApiUrl);
    const [errorMessage, setErrorMessage] = useState<string>();

    const navigate = useNavigate();

    const [sessionDetails, setSessionDetails] = useState<Partial<SessionData>>({ ...SessionInitialState });

    const { show, hide } = useLoader();

    useEffect(() => {
        const sessionData = StorageService.getSessionData();
        if (sessionData) {
            setSessionDetails(sessionData);
        }
    }, []);

    const fetchSessionFromAPI = async () => {
        show();
        let errorMessage = '';

        apiService
            .getSession()
            .then((response) => setSessionDetails?.(response))
            .catch((error: ErrorResponse) => {
                if (error.errors?.length) {
                    errorMessage =
                        translations.errors_while_fetching_data + error.errors.map((err) => err.message).join(', ');
                } else {
                    errorMessage = translations.there_was_an_error_fetching_data_did_you_mock_api;
                }
            })
            .finally(() => {
                setErrorMessage(errorMessage);
                hide();
            });
    };

    const pasteData = () => {
        let error = '';
        navigator.clipboard.readText().then((text) => {
            try {
                const data = JSON.parse(text);
                if (data?.assetUrl && data.clientApiUrl && data.clientSessionId && data.customerId) {
                    setSessionDetails?.({
                        assetUrl: data.assetUrl,
                        clientApiUrl: data.clientApiUrl,
                        clientSessionId: data.clientSessionId,
                        customerId: data.customerId
                    });
                    return;
                }
                // eslint-disable-next-line @typescript-eslint/no-unused-vars
            } catch (e) {
                error = translations.the_clipboard_does_not_contain_valid_data;
            }

            setErrorMessage(error);
        });
    };

    const handleChangeSessionDetails = (value: string, prop: keyof SessionData) => {
        setSessionDetails?.((prev) => ({
            ...prev,
            [prop]: value
        }));
    };

    const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
        e.stopPropagation();
        e.preventDefault();
        if (
            !sessionDetails?.assetUrl ||
            !sessionDetails.clientApiUrl ||
            !sessionDetails.clientSessionId ||
            !sessionDetails.customerId
        ) {
            setErrorMessage(translations.please_fill_in_all_the_data);
        } else {
            StorageService.clear();
            StorageService.setSession(sessionDetails as SessionData);

            navigate('/payment');
        }
    };

    return (
        <div className='page'>
            <Logo />
            <h1>{translations.initialize_session}</h1>
            <p>
                {translations.to_process_the_payment_using_services_provided_by_the_online_payments_platform +
                    translations.information_must_be_provided_as_a_merchant}
            </p>
            <div className='flex column mt-1'>
                <form className='form' id='sessionForm' onSubmit={handleSubmit}>
                    <Input
                        label={translations.asset_url}
                        id='assetUrl'
                        type='url'
                        required={true}
                        value={sessionDetails?.assetUrl}
                        onChange={(e) => handleChangeSessionDetails(e, 'assetUrl')}
                    />
                    <Input
                        label={translations.client_api_url}
                        id='clientApiUrl'
                        type='url'
                        required={true}
                        value={sessionDetails?.clientApiUrl}
                        onChange={(e) => handleChangeSessionDetails(e, 'clientApiUrl')}
                    />
                    <Input
                        label={translations.client_session_id}
                        id='clientSessionId'
                        type='text'
                        required={true}
                        value={sessionDetails?.clientSessionId}
                        onChange={(e) => handleChangeSessionDetails(e, 'clientSessionId')}
                    />
                    <Input
                        label={translations.customer_id}
                        id='customerId'
                        type='text'
                        required={true}
                        value={sessionDetails?.customerId}
                        onChange={(e) => handleChangeSessionDetails(e, 'customerId')}
                    />
                    <button className='button primary' type='submit'>
                        {translations.start_session}
                    </button>
                </form>
                <div className='label'>{translations.get_session_details_from}</div>
                <div className='flex row center'>
                    <button className='button' type='button' onClick={pasteData}>
                        {translations.clipboard}
                    </button>
                    {useMockApi && (
                        <button className='button' type='button' onClick={fetchSessionFromAPI}>
                            {translations.mock_api}
                        </button>
                    )}
                </div>
            </div>
            <div className='error mt-1' id='errorMessage'>
                {errorMessage}
            </div>
        </div>
    );
};

export default SessionPage;
