// examples/svelte/src/pages/GooglePayPage.svelte
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script lang="ts">
    import { onMount } from 'svelte';
    import { goto } from '$app/navigation';
    import StorageService from '@shared/services/StorageService';
    import NumberFormatter from '@shared/utilities/NumberFormatter';
    import EncryptionService from '@shared/services/EncryptionService';
    import {
        type PaymentContextWithAmount,
        PaymentProduct,
        PaymentRequest,
        OnlinePaymentSdk, init
    } from 'onlinepayments-sdk-client-js';
    import { translations } from '../translations/translations';
    import Logo from '../components/Logo/Logo.svelte';
    import { loader } from '../stores/loader';
    import { resolve } from '$app/paths';
    import PaymentProductService from '@shared/services/PaymentProductService';
    import Loader from '../components/Loader/Loader.svelte';

    let paymentContext: PaymentContextWithAmount | null = null;
    let paymentProduct: PaymentProduct | null = null;
    let sdk: OnlinePaymentSdk;
    let isRecurring = false;
    let errorMessage = '';
    let paymentsClient: GooglePaymentsClient;
    let baseRequest: PaymentDataRequest;
    let isLoading = true;

    /**
     * Creates a base PaymentDataRequest object for Google Pay.
     *
     * @param {string[]} allowedNetworks - Allowed card networks (e.g., VISA, MASTERCARD).
     * @returns {PaymentDataRequest} The base PaymentDataRequest object.
     */
    const createBaseRequest = (allowedNetworks: string[]): PaymentDataRequest => ({
        apiVersion: 2,
        apiVersionMinor: 0,
        allowedPaymentMethods: [
            {
                type: 'CARD',
                parameters: {
                    allowedAuthMethods: ['PAN_ONLY', 'CRYPTOGRAM_3DS'],
                    allowedCardNetworks: allowedNetworks
                }
            }
        ]
    });

    /**
     * Encrypts Google Pay token and stores it in StorageService.
     * Navigates to the "finalize" payment page if successful.
     *
     * @param {string} [token] - The token received from Google Pay.
     */
    const handleEncryptGooglePayData = (token?: string): void => {
        if (!token || !paymentProduct || !sdk) {
            return;
        }

        const pr = new PaymentRequest(paymentProduct);
        pr.setTokenize(isRecurring);
        pr.setValue('encryptedPaymentData', token);

        if (pr.validate().isValid) {
            EncryptionService.encrypt(sdk, pr)
                .then(() => {
                    StorageService.setPaymentRequest(pr);

                    goto(resolve('/payment/finalize/'));
                })
                .catch((errors) => {
                    errorMessage = 'Errors: ' + JSON.stringify(errors);
                });
        }
    };


    /**
     * Returns the Google Pay card payment method configuration for the current payment product.
     *
     * @returns {any} Card payment method object for PaymentDataRequest.
     */
    const getCardPaymentMethod = () => {
        return ({
            type: 'CARD',
            parameters: {
                allowedAuthMethods: ['PAN_ONLY', 'CRYPTOGRAM_3DS'],
                allowedCardNetworks:
                    paymentProduct?.paymentProduct320SpecificData?.networks ?? ['VISA', 'MASTERCARD']
            },
            tokenizationSpecification: {
                type: 'PAYMENT_GATEWAY',
                parameters: {
                    gateway: paymentProduct?.paymentProduct320SpecificData?.gateway?.trim().toLowerCase() ?? 'gateway',
                    gatewayMerchantId: 'DemoMerchant'
                }
            }
        });
    };

    /**
     * Builds a full PaymentDataRequest object for Google Pay with transaction info.
     *
     * @returns {PaymentDataRequest} The full PaymentDataRequest object.
     */
    const getPaymentDataRequest = (): PaymentDataRequest => ({
        apiVersion: 2,
        apiVersionMinor: 0,
        allowedPaymentMethods: [getCardPaymentMethod()],
        merchantInfo: { merchantName: 'Demo Merchant' },
        transactionInfo: {
            totalPriceStatus: 'FINAL',
            totalPrice: NumberFormatter.formatAmountForGooglePay(
                paymentContext!.amountOfMoney.currencyCode ?? 'EUR',
                paymentContext!.amountOfMoney.amount ?? 1000
            ),
            currencyCode: paymentContext!.amountOfMoney.currencyCode,
            countryCode: paymentContext!.countryCode
        }
    });

    /**
     * Handler for Google Pay button click.
     * Loads the Google Pay sheet and encrypts the token on success.
     */
    const onGooglePayButtonClicked = (): void => {
        if (!paymentContext || !paymentProduct) {
            return;
        }

        paymentsClient
            .loadPaymentData(getPaymentDataRequest())
            .then((paymentData) => {
                const token = paymentData?.paymentMethodData?.tokenizationData?.token;
                handleEncryptGooglePayData(token);
            })
            .catch((err) => {
                console.error(err);
                errorMessage = err?.message ?? 'Error loading Google Pay sheet';
            });
    };

    const initData = async () => {
        loader.show();
        const s = StorageService.getSessionData();

        if (!s) {
            goto(resolve('/'));

            return;
        }

        const productId = StorageService.getPaymentProductId();
        const context = StorageService.getPaymentContext()

        if (!productId || !context) {
            goto(resolve('/payment/'));

            return;
        }

        paymentContext = StorageService.getPaymentContext();

        sdk = init(s)

        paymentProduct = await PaymentProductService.getPaymentProduct(sdk, productId, context)

        if(!paymentProduct){
            goto(resolve('/payment'));

            return;
        }

        baseRequest = createBaseRequest(
            paymentProduct?.paymentProduct320SpecificData?.networks ?? ['VISA', 'MASTERCARD']
        );

        paymentsClient = new google.payments.api.PaymentsClient({ environment: 'TEST' });

        paymentsClient
            .isReadyToPay(baseRequest)
            .then((res) => {
                if (res.result) {
                    const container = document.getElementById('googlePay');
                    if (container) {
                        const button = paymentsClient.createButton({ onClick: onGooglePayButtonClicked });
                        container.appendChild(button);
                    }
                } else {
                    errorMessage = 'Google Pay not available';
                }
            })
            .catch((err) => {
                console.error(err);
                errorMessage = 'Error loading Google Pay Integration';
            });

        loader.hide();
        isLoading = false;
    }

    onMount(() => {
        initData().catch(error => console.error(error))
    });
</script>

<Loader />

<div class="page flex column center">
    <Logo />
    <h1 class="m-0">{translations.pay_with_google_pay}</h1>
    <p class="self-start m-0">
        <strong>
            {translations.total_amount}
            {#if paymentContext}
                {NumberFormatter.formatAmount(paymentContext.amountOfMoney.currencyCode, paymentContext.amountOfMoney.amount)}
                {paymentContext.amountOfMoney.currencyCode}
            {/if}
        </strong>
    </p>

    <a class="button link self-start" href={resolve('/payment')}>
        {translations.back_to_payment_method_selection}
    </a>

    <div id="googlePay" class="form form-max-height flex column center m-0 {isLoading ? 'invisible' : ''}"></div>

    <div class="error">{errorMessage}</div>
</div>

// examples/vue/src/pages/GooglePay/GooglePayPage.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import { computed, onMounted, ref, shallowRef, toRaw } from 'vue';
import {
    init,
    type OnlinePaymentSdk,
    type PaymentContextWithAmount,
    PaymentProduct,
    PaymentRequest
} from 'onlinepayments-sdk-client-js';
import { useRouter } from 'vue-router';
import RouterService from '../../services/RouterService.ts';
import LoaderService from '../../services/LoaderService.ts';
import StorageService from '@shared/services/StorageService';
import NumberFormatter from '@shared/utilities/NumberFormatter';
import EncryptionService from '@shared/services/EncryptionService';
import translations from '../../translations/translations.ts';
import Logo from '../../components/Logo/Logo.vue';
import PaymentProductService from '@shared/services/PaymentProductService.ts';

declare global {
    interface Window {
        google?: any;
    }
}

const router = useRouter();
const { redirectToPage } = RouterService(router);

const googlePayContainer = ref<HTMLElement | null>(null);

const sdk = shallowRef<OnlinePaymentSdk>();
const paymentProduct = ref<PaymentProduct | null>();

const paymentContext = ref<PaymentContextWithAmount>();

const errorMessage = ref('');

let paymentsClient: any;

const isLoading = ref(true);

const ENVIRONMENT = 'TEST' as const;
const baseRequest = { apiVersion: 2, apiVersionMinor: 0 } as const;
const baseAllowedCardNetworks = ['MASTERCARD', 'VISA'] as const;
const baseAllowedAuthMethods = ['PAN_ONLY', 'CRYPTOGRAM_3DS'] as const;

const initData = async () => {
    LoaderService.show();
    const sessionDetails = StorageService.getSessionData();
    const productId = StorageService.getPaymentProductId();
    const context = StorageService.getPaymentContext();

    if (sessionDetails) {
        sdk.value = init(sessionDetails);
    }

    if (context) {
        paymentContext.value = context;
    }

    if (productId) {
        paymentProduct.value = await PaymentProductService.getPaymentProduct(sdk.value!, Number(productId), context!);
    }

    if (!paymentProduct.value) {
        redirectToPage('/payment');
    }

    if (!window.google?.payments?.api) {
        errorMessage.value = translations.error_loading_google_pay;
        return;
    }

    paymentsClient = new window.google.payments.api.PaymentsClient({
        environment: ENVIRONMENT
    });

    void isGooglePayButtonReady();
    LoaderService.hide();
    isLoading.value = false;
};

onMounted(() => {
    initData().catch((error) => console.log(error));
});

const tokenizationSpecification = computed(() => {
    return {
        type: 'PAYMENT_GATEWAY',
        parameters: {
            gateway: paymentProduct.value?.paymentProduct320SpecificData?.gateway?.trim().toLowerCase() ?? 'gateway',
            gatewayMerchantId: 'DemoMerchant'
        }
    };
});

const getCardPaymentMethod = () => {
    const networks = paymentProduct.value?.paymentProduct320SpecificData?.networks ?? baseAllowedCardNetworks;

    return {
        type: 'CARD',
        parameters: {
            allowedAuthMethods: baseAllowedAuthMethods,
            allowedCardNetworks: networks
        },
        tokenizationSpecification: tokenizationSpecification.value
    };
};

const isGooglePayButtonReady = async () => {
    const baseCardPaymentMethod = {
        type: 'CARD',
        parameters: {
            allowedAuthMethods: baseAllowedAuthMethods,
            allowedCardNetworks: baseAllowedCardNetworks
        }
    };

    try {
        const isReady = await paymentsClient.isReadyToPay({
            ...baseRequest,
            allowedPaymentMethods: [baseCardPaymentMethod]
        });

        if (isReady.result) {
            const button = paymentsClient.createButton({
                onClick: () => handleClick(),
                allowedPaymentMethods: [getCardPaymentMethod()],
                buttonType: 'long',
                buttonColor: 'black'
            });

            if (googlePayContainer.value) {
                googlePayContainer.value.appendChild(button);
            }
        } else {
            errorMessage.value = translations.google_pay_not_ready;
        }
    } catch (error) {
        console.error(error);
    }
};

const getPaymentDataRequest = () => {
    return {
        ...baseRequest,
        allowedPaymentMethods: [getCardPaymentMethod()],
        merchantInfo: {
            merchantName: 'DemoMerchant'
        },
        transactionInfo: {
            totalPriceStatus: 'FINAL',
            totalPrice: NumberFormatter.formatAmountForGooglePay(
                paymentContext.value?.amountOfMoney.currencyCode ?? 'EUR',
                paymentContext.value?.amountOfMoney.amount ?? 1000
            ),
            currencyCode: paymentContext.value?.amountOfMoney.currencyCode,
            countryCode: paymentContext.value?.countryCode
        }
    };
};

const handleClick = async () => {
    try {
        const paymentData = await paymentsClient.loadPaymentData(getPaymentDataRequest());
        const token = paymentData?.paymentMethodData?.tokenizationData?.token;

        if (!paymentProduct.value) {
            errorMessage.value = translations.payment_product_not_found;
            return;
        }

        const paymentRequest = new PaymentRequest(toRaw(paymentProduct.value) as PaymentProduct);
        paymentRequest.setValue('encryptedPaymentData', token);

        if (paymentRequest.validate().isValid && sdk.value) {
            try {
                await EncryptionService.encrypt(sdk.value, paymentRequest);
                StorageService.setPaymentRequest(paymentRequest);
                redirectToPage('/payment/finalize');
            } catch (errors) {
                errorMessage.value = 'Errors: ' + JSON.stringify(errors);
            }
        }
    } catch (err) {
        console.error(err);
    }
};
</script>

<template>
    <div class="page flex column center">
        <Logo />
        <h1 class="m-0">{{ translations.pay_with_google_pay }}</h1>
        <p class="self-start m-0">
            <strong>
                {{ translations.total_amount }}
                {{
                    paymentContext?.amountOfMoney?.currencyCode &&
                    paymentContext?.amountOfMoney.amount &&
                    NumberFormatter.formatAmount(
                        paymentContext.amountOfMoney.currencyCode,
                        paymentContext.amountOfMoney.amount
                    )
                }}
                {{ paymentContext?.amountOfMoney?.currencyCode }}
            </strong>
        </p>
        <RouterLink to="/payment/" class="button link self-start">
            {{ translations.back_to_payment_method_selection }}
        </RouterLink>
        <div
            class="form flex column center m-0"
            :class="{
                form: true,
                flex: true,
                column: true,
                center: true,
                'm-0': true,
                'form-max-height': true,
                invisible: isLoading
            }"
        >
            <div ref="googlePayContainer" class="gpay-container"></div>
            <div v-if="errorMessage" class="error">{{ translations.google_pay_not_ready }}</div>
        </div>
        <div id="error" class="error">{{ errorMessage }}</div>
    </div>
</template>
