// examples/react/src/pages/GooglePay/GooglePayPage.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { useEffect, useMemo, useRef, useState } from 'react';
import { useLoader } from '../../components/Loader/Loader.tsx';
import { Link, useNavigate } from 'react-router-dom';
import GooglePayButton from '@google-pay/button-react';
import StorageService from '@shared/services/StorageService';
import {
    init,
    type OnlinePaymentSdk,
    type PaymentContextWithAmount,
    PaymentProduct,
    PaymentRequest,
    type SessionData
} from 'onlinepayments-sdk-client-js';
import NumberFormatter from '@shared/utilities/NumberFormatter';
import EncryptionService from '@shared/services/EncryptionService';
import translations from '../../translations/translations.ts';
import Logo from '../../components/Logo/Logo.tsx';
import PaymentProductService from '@shared/services/PaymentProductService.ts';

const GooglePayPage = () => {
    const { show, hide } = useLoader();
    const sdk = useRef<OnlinePaymentSdk>(null);
    const navigate = useNavigate();

    const [paymentContext, setPaymentContext] = useState<PaymentContextWithAmount>();
    const [paymentProduct, setPaymentProduct] = useState<PaymentProduct>();

    const [errorMessage, setErrorMessage] = useState('');

    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const initData = async () => {
            show();

            const sessionData = StorageService.getSessionData();
            const context = StorageService.getPaymentContext();

            if (!sessionData || !context) {
                hide();
                navigate('/');
                return;
            }

            setPaymentContext(context);
            sdk.current = init(sessionData as SessionData);

            const paymentProductId = StorageService.getPaymentProductId();

            if (paymentProductId) {
                const product = await PaymentProductService.getPaymentProduct(
                    sdk.current,
                    Number(paymentProductId),
                    context
                );

                if (product) {
                    setPaymentProduct(product);
                    setIsLoading(false);
                    hide();

                    return;
                }

                setErrorMessage(translations.payment_product_not_found);
            }

            hide();
            setIsLoading(false);
            navigate('/payment');
        };

        initData().catch((error) => console.error(error));
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const googlePaymentRequest = useMemo(() => {
        if (!paymentProduct) {
            return null;
        }

        return {
            apiVersion: 2,
            apiVersionMinor: 0,
            allowedPaymentMethods: [
                {
                    type: 'CARD',
                    parameters: {
                        allowedAuthMethods: ['PAN_ONLY', 'CRYPTOGRAM_3DS'],
                        allowedCardNetworks: (paymentProduct.paymentProduct320SpecificData
                            ?.networks as google.payments.api.CardNetwork[]) ?? ['VISA', 'MASTERCARD']
                    },
                    tokenizationSpecification: {
                        type: 'PAYMENT_GATEWAY',
                        parameters: {
                            gateway: paymentProduct.paymentProduct320SpecificData?.gateway ?? 'example',
                            gatewayMerchantId: 'DemoMerchant'
                        }
                    }
                }
            ] satisfies google.payments.api.PaymentMethodSpecification[],
            merchantInfo: {
                merchantName: 'Demo merchant',
                merchantId: 'demoMerchant'
            } as google.payments.api.MerchantInfo,
            transactionInfo: {
                totalPriceStatus: 'FINAL',
                totalPrice: NumberFormatter.formatAmountForGooglePay(
                    paymentContext?.amountOfMoney.currencyCode ?? 'EUR',
                    paymentContext?.amountOfMoney.amount ?? 1000
                ),
                currencyCode: paymentContext?.amountOfMoney?.currencyCode,
                countryCode: paymentContext?.countryCode
            } as google.payments.api.TransactionInfo
        };
    }, [
        paymentContext?.amountOfMoney.amount,
        paymentContext?.amountOfMoney.currencyCode,
        paymentContext?.countryCode,
        paymentProduct
    ]);

    const handleEncryptGooglePayData = (paymentData: google.payments.api.PaymentData) => {
        const token = paymentData.paymentMethodData?.tokenizationData?.token;

        if (!token) {
            return;
        }

        const paymentRequest = new PaymentRequest(paymentProduct!);

        paymentRequest.setValue('encryptedPaymentData', token);

        if (paymentRequest.validate().isValid && sdk.current) {
            EncryptionService.encrypt(sdk.current, paymentRequest)
                .then(() => {
                    StorageService.setPaymentRequest(paymentRequest);
                    navigate('/payment/finalize');
                })
                .catch((errors) => {
                    setErrorMessage('Errors: ' + JSON.stringify(errors));
                });
        }
    };

    return (
        <div className='page flex column center'>
            <Logo />
            <h1 className='m-0'>{translations.pay_with_google_pay}</h1>
            <p className='self-start m-0'>
                <strong>
                    {translations.total_amount}{' '}
                    {paymentContext &&
                        paymentContext.amountOfMoney.amount &&
                        paymentContext.amountOfMoney.currencyCode &&
                        NumberFormatter.formatAmount(
                            paymentContext.amountOfMoney.currencyCode,
                            paymentContext.amountOfMoney.amount
                        )}{' '}
                    {paymentContext?.amountOfMoney?.currencyCode}
                </strong>
            </p>
            <Link to='/payment/' className='button link self-start'>
                {translations.back_to_payment_method_selection}
            </Link>
            <div className={`form flex column center m-0 form-max-height ${isLoading ? 'invisible' : ''}`}>
                {googlePaymentRequest && paymentProduct ? (
                    <GooglePayButton
                        environment='TEST'
                        buttonColor='default'
                        buttonType='pay'
                        existingPaymentMethodRequired={false}
                        onLoadPaymentData={(paymentData) => handleEncryptGooglePayData(paymentData)}
                        onError={(error) => {
                            if ('statusMessage' in error) {
                                setErrorMessage(error.statusMessage);
                            } else {
                                setErrorMessage(error.message);
                            }
                        }}
                        paymentRequest={googlePaymentRequest}
                    />
                ) : (
                    !isLoading && <div className='error'>{translations.google_pay_not_ready}</div>
                )}
            </div>
            <div id='error' className='error'>
                {errorMessage}
            </div>
        </div>
    );
};

export default GooglePayPage;

// examples/vue/src/pages/GooglePay/GooglePayPage.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import { computed, onMounted, ref, shallowRef, toRaw } from 'vue';
import {
    init,
    type OnlinePaymentSdk,
    type PaymentContextWithAmount,
    PaymentProduct,
    PaymentRequest
} from 'onlinepayments-sdk-client-js';
import { useRouter } from 'vue-router';
import RouterService from '../../services/RouterService.ts';
import LoaderService from '../../services/LoaderService.ts';
import StorageService from '@shared/services/StorageService';
import NumberFormatter from '@shared/utilities/NumberFormatter';
import EncryptionService from '@shared/services/EncryptionService';
import translations from '../../translations/translations.ts';
import Logo from '../../components/Logo/Logo.vue';
import PaymentProductService from '@shared/services/PaymentProductService.ts';

declare global {
    interface Window {
        google?: any;
    }
}

const router = useRouter();
const { redirectToPage } = RouterService(router);

const googlePayContainer = ref<HTMLElement | null>(null);

const sdk = shallowRef<OnlinePaymentSdk>();
const paymentProduct = ref<PaymentProduct | null>();

const paymentContext = ref<PaymentContextWithAmount>();

const errorMessage = ref('');

let paymentsClient: any;

const isLoading = ref(true);

const ENVIRONMENT = 'TEST' as const;
const baseRequest = { apiVersion: 2, apiVersionMinor: 0 } as const;
const baseAllowedCardNetworks = ['MASTERCARD', 'VISA'] as const;
const baseAllowedAuthMethods = ['PAN_ONLY', 'CRYPTOGRAM_3DS'] as const;

const initData = async () => {
    LoaderService.show();
    const sessionDetails = StorageService.getSessionData();
    const productId = StorageService.getPaymentProductId();
    const context = StorageService.getPaymentContext();

    if (sessionDetails) {
        sdk.value = init(sessionDetails);
    }

    if (context) {
        paymentContext.value = context;
    }

    if (productId) {
        paymentProduct.value = await PaymentProductService.getPaymentProduct(sdk.value!, Number(productId), context!);
    }

    if (!paymentProduct.value) {
        redirectToPage('/payment');
    }

    if (!window.google?.payments?.api) {
        errorMessage.value = translations.error_loading_google_pay;
        return;
    }

    paymentsClient = new window.google.payments.api.PaymentsClient({
        environment: ENVIRONMENT
    });

    void isGooglePayButtonReady();
    LoaderService.hide();
    isLoading.value = false;
};

onMounted(() => {
    initData().catch((error) => console.log(error));
});

const tokenizationSpecification = computed(() => {
    return {
        type: 'PAYMENT_GATEWAY',
        parameters: {
            gateway: paymentProduct.value?.paymentProduct320SpecificData?.gateway?.trim().toLowerCase() ?? 'gateway',
            gatewayMerchantId: 'DemoMerchant'
        }
    };
});

const getCardPaymentMethod = () => {
    const networks = paymentProduct.value?.paymentProduct320SpecificData?.networks ?? baseAllowedCardNetworks;

    return {
        type: 'CARD',
        parameters: {
            allowedAuthMethods: baseAllowedAuthMethods,
            allowedCardNetworks: networks
        },
        tokenizationSpecification: tokenizationSpecification.value
    };
};

const isGooglePayButtonReady = async () => {
    const baseCardPaymentMethod = {
        type: 'CARD',
        parameters: {
            allowedAuthMethods: baseAllowedAuthMethods,
            allowedCardNetworks: baseAllowedCardNetworks
        }
    };

    try {
        const isReady = await paymentsClient.isReadyToPay({
            ...baseRequest,
            allowedPaymentMethods: [baseCardPaymentMethod]
        });

        if (isReady.result) {
            const button = paymentsClient.createButton({
                onClick: () => handleClick(),
                allowedPaymentMethods: [getCardPaymentMethod()],
                buttonType: 'long',
                buttonColor: 'black'
            });

            if (googlePayContainer.value) {
                googlePayContainer.value.appendChild(button);
            }
        } else {
            errorMessage.value = translations.google_pay_not_ready;
        }
    } catch (error) {
        console.error(error);
    }
};

const getPaymentDataRequest = () => {
    return {
        ...baseRequest,
        allowedPaymentMethods: [getCardPaymentMethod()],
        merchantInfo: {
            merchantName: 'DemoMerchant'
        },
        transactionInfo: {
            totalPriceStatus: 'FINAL',
            totalPrice: NumberFormatter.formatAmountForGooglePay(
                paymentContext.value?.amountOfMoney.currencyCode ?? 'EUR',
                paymentContext.value?.amountOfMoney.amount ?? 1000
            ),
            currencyCode: paymentContext.value?.amountOfMoney.currencyCode,
            countryCode: paymentContext.value?.countryCode
        }
    };
};

const handleClick = async () => {
    try {
        const paymentData = await paymentsClient.loadPaymentData(getPaymentDataRequest());
        const token = paymentData?.paymentMethodData?.tokenizationData?.token;

        if (!paymentProduct.value) {
            errorMessage.value = translations.payment_product_not_found;
            return;
        }

        const paymentRequest = new PaymentRequest(toRaw(paymentProduct.value) as PaymentProduct);
        paymentRequest.setValue('encryptedPaymentData', token);

        if (paymentRequest.validate().isValid && sdk.value) {
            try {
                await EncryptionService.encrypt(sdk.value, paymentRequest);
                StorageService.setPaymentRequest(paymentRequest);
                redirectToPage('/payment/finalize');
            } catch (errors) {
                errorMessage.value = 'Errors: ' + JSON.stringify(errors);
            }
        }
    } catch (err) {
        console.error(err);
    }
};
</script>

<template>
    <div class="page flex column center">
        <Logo />
        <h1 class="m-0">{{ translations.pay_with_google_pay }}</h1>
        <p class="self-start m-0">
            <strong>
                {{ translations.total_amount }}
                {{
                    paymentContext?.amountOfMoney?.currencyCode &&
                    paymentContext?.amountOfMoney.amount &&
                    NumberFormatter.formatAmount(
                        paymentContext.amountOfMoney.currencyCode,
                        paymentContext.amountOfMoney.amount
                    )
                }}
                {{ paymentContext?.amountOfMoney?.currencyCode }}
            </strong>
        </p>
        <RouterLink to="/payment/" class="button link self-start">
            {{ translations.back_to_payment_method_selection }}
        </RouterLink>
        <div
            class="form flex column center m-0"
            :class="{
                form: true,
                flex: true,
                column: true,
                center: true,
                'm-0': true,
                'form-max-height': true,
                invisible: isLoading
            }"
        >
            <div ref="googlePayContainer" class="gpay-container"></div>
            <div v-if="errorMessage" class="error">{{ translations.google_pay_not_ready }}</div>
        </div>
        <div id="error" class="error">{{ errorMessage }}</div>
    </div>
</template>
