// examples/react/src/pages/FinalizePayment/FinalizePaymentPage.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import Logo from '../../components/Logo/Logo.tsx';
import { mockApiUrl, useMockApi } from '../../config.ts';
import { useEffect, useRef, useState } from 'react';
import {
    type ErrorResponse,
    init,
    OnlinePaymentSdk,
    type PaymentContextWithAmount
} from 'onlinepayments-sdk-client-js';
import StorageService from '@shared/services/StorageService';
import { useLoader } from '../../components/Loader/Loader.tsx';
import { useNavigate } from 'react-router-dom';
import ApiService from '@shared/services/ApiService';
import translations from '../../translations/translations.ts';
import { createPaymentApiDocumentationLink, serverToServerDocumentationLink } from '@shared/constants/links';
import type { EncryptedData } from '@shared/types/CreatePaymentRequest';

type PaymentData = {
    type: 'encrypted' | 'raw';
    data: string;
};

const FinalizePaymentPage = () => {
    const sdk = useRef<OnlinePaymentSdk>(null);

    const { show, hide } = useLoader();
    const navigate = useNavigate();

    const [paymentContext, setPaymentContext] = useState<PaymentContextWithAmount>();

    const [paymentData, setPaymentData] = useState<PaymentData>();
    const [paymentResponse, setPaymentResponse] = useState('');

    const [errorMessage, setErrorMessage] = useState<string>('');

    const [paymentRequest] = useState(() => JSON.stringify(StorageService.getPaymentRequest() ?? '', null, 2));

    useEffect(() => {
        show();
        const sessionData = StorageService.getSessionData();
        if (!sessionData) {
            hide();
            navigate('/');
        } else {
            sdk.current = init(sessionData);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
        if (
            !StorageService.getPaymentProductId() ||
            (!StorageService.getEncryptedData() && !StorageService.getCardPaymentSpecificData())
        ) {
            hide();
            navigate(`/payment`);
            return;
        }

        if (StorageService.getCardPaymentSpecificData()) {
            setPaymentData({
                type: 'raw',
                data: JSON.stringify(StorageService.getCardPaymentSpecificData(), null, 2)
            });
        } else {
            setPaymentData({ type: 'encrypted', data: StorageService.getEncryptedData() ?? '' });
        }

        if (StorageService.getPaymentContext()) {
            setPaymentContext(StorageService.getPaymentContext()!);
        }

        hide();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const handleRestartSession = () => {
        StorageService.clear();
        navigate('/');
    };

    const processPayment = async () => {
        let errorMessage = '';
        const apiService = ApiService(mockApiUrl);

        show();
        apiService
            .createPayment({
                ...paymentContext,
                ...((StorageService.getCardPaymentSpecificData() && StorageService.getAccountOnFileId()
                    ? { ...StorageService.getCardPaymentSpecificData() }
                    : { data: StorageService.getEncryptedData() }) as EncryptedData)
            })
            .then((response) => {
                setPaymentResponse(JSON.stringify(response, null, 2));
            })
            .catch((error: ErrorResponse) => {
                if (error.errors?.length) {
                    errorMessage =
                        translations.errors_while_fetching_data + error.errors.map((err) => err.message).join(', ');
                } else {
                    errorMessage = translations.there_was_an_error_fetching_data_did_you_mock_api;
                }
            })
            .finally(() => {
                setErrorMessage(errorMessage);
                hide();
            });
    };

    return (
        <div className='page'>
            <Logo />
            <h1>{translations.complete_payment}</h1>
            <div className='form'>
                <div className='label'>{translations.payment_request}</div>
                <textarea
                    className='small'
                    rows={10}
                    aria-autocomplete='none'
                    aria-multiline='true'
                    autoCapitalize='off'
                    autoCorrect='off'
                    data-enable-grammarly='false'
                    data-gramm='false'
                    spellCheck='false'
                    defaultValue={paymentRequest}
                />
                <>
                    <div className='label'>
                        {paymentData?.type === 'raw' ? translations.payload : translations.encrypted_string}
                    </div>
                    <textarea
                        className='small'
                        rows={10}
                        aria-autocomplete='none'
                        aria-multiline='false'
                        autoCapitalize='off'
                        autoCorrect='off'
                        data-enable-grammarly='false'
                        data-gramm='false'
                        spellCheck='false'
                        defaultValue={paymentData?.data}
                    />
                </>
                {useMockApi && (
                    <button className='button primary' type='button' onClick={processPayment}>
                        {translations.submit_to_mock_api}
                    </button>
                )}
                <div className='error'>{errorMessage}</div>
                {paymentResponse && (
                    <div>
                        <div className='label'>{translations.payment_response}</div>
                        <textarea
                            className='small'
                            rows={10}
                            aria-autocomplete='none'
                            aria-multiline='false'
                            autoCapitalize='off'
                            autoCorrect='off'
                            data-enable-grammarly='false'
                            data-gramm='false'
                            spellCheck='false'
                            defaultValue={paymentResponse ?? ''}
                        />
                    </div>
                )}
            </div>
            <button className='button primary mt-1' type='button' onClick={handleRestartSession}>
                {translations.restart_session}
            </button>
            <div className='flex column start mt-1'>
                <span>{translations.to_learn_more_about_creating_payment_check_the_following_link}</span>
                <a className='button link' href={createPaymentApiDocumentationLink}>
                    {translations.create_payment_api_documentation}
                </a>
                <a className='button link' href={serverToServerDocumentationLink}>
                    {translations.server_to_server_integration}
                </a>
            </div>
        </div>
    );
};

export default FinalizePaymentPage;

// examples/vue/src/pages/FinalizePayment/FinalizePaymentPage.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import { onMounted, ref, shallowRef } from 'vue';
import { useRouter } from 'vue-router';
import {
    type ErrorResponse,
    init,
    type OnlinePaymentSdk,
    type PaymentContextWithAmount
} from 'onlinepayments-sdk-client-js';
import { mockApiUrl, useMockApi } from '../../config.ts';
import StorageService from '@shared/services/StorageService';
import ApiService from '@shared/services/ApiService';
import { createPaymentApiDocumentationLink, serverToServerDocumentationLink } from '@shared/constants/links';
import LoaderService from '../../services/LoaderService.ts';
import translations from '../../translations/translations';
import type { CardPaymentSpecificData, EncryptedData } from '@shared/types/CreatePaymentRequest';
import Logo from '../../components/Logo/Logo.vue';

type PaymentData = {
    type: 'encrypted' | 'raw';
    data: string;
};

const sdk = shallowRef<OnlinePaymentSdk>();

const router = useRouter();

const paymentContext = ref<PaymentContextWithAmount>();
const paymentData = ref<PaymentData>();
const paymentResponse = ref<string>('');
const errorMessage = ref<string>('');

const paymentRequest = ref<string>(JSON.stringify(StorageService.getPaymentRequest() ?? '', null, 2));

onMounted(() => {
    const sessionDetails = StorageService.getSessionData();
    const context = StorageService.getPaymentContext();
    const cardPaymentSpecificData = StorageService.getCardPaymentSpecificData();

    if (sessionDetails) {
        sdk.value = init(sessionDetails);
    }

    if (context) {
        paymentContext.value = context;
    }

    if (cardPaymentSpecificData) {
        paymentData.value = {
            type: 'raw',
            data: JSON.stringify(cardPaymentSpecificData, null, 2)
        };
    } else {
        paymentData.value = {
            type: 'encrypted',
            data: StorageService.getEncryptedData() ?? ''
        };
    }
});

const handleRestartSession = () => {
    StorageService.clear();
    router.push('/');
};

const processPayment = async () => {
    let message = '';

    LoaderService.show();
    ApiService(mockApiUrl)
        .createPayment({
            ...paymentContext.value,
            ...((StorageService.getCardPaymentSpecificData()
                ? ({ ...StorageService.getCardPaymentSpecificData() } as CardPaymentSpecificData)
                : { data: StorageService.getEncryptedData() }) as EncryptedData)
        })
        .then((response) => {
            paymentResponse.value = JSON.stringify(response, null, 2);
        })
        .catch((error: ErrorResponse) => {
            if (error.errors?.length) {
                message = translations.errors_while_fetching_data + error.errors.map((err) => err.message).join(', ');
            } else {
                message = translations.there_was_an_error_fetching_data_did_you_mock_api;
            }
        })
        .finally(() => {
            errorMessage.value = message;
            LoaderService.hide();
        });
};
</script>
<template>
    <div class="page">
        <Logo />
        <h1>{{ translations.complete_payment }}</h1>
        <div class="form">
            <div class="label">{{ translations.payment_request }}</div>
            <textarea
                class="small"
                :rows="10"
                aria-autocomplete="none"
                aria-multiline="true"
                autocapitalize="off"
                autocorrect="off"
                data-enable-grammarly="false"
                data-gramm="false"
                spellcheck="false"
                :value="paymentRequest"
            />
            <template v-if="paymentData">
                <div class="label">
                    {{ paymentData.type === 'raw' ? translations.payload : translations.encrypted_string }}
                </div>
                <textarea
                    class="small"
                    :rows="10"
                    aria-autocomplete="none"
                    aria-multiline="false"
                    autocapitalize="off"
                    autocorrect="off"
                    data-enable-grammarly="false"
                    data-gramm="false"
                    spellcheck="false"
                    :value="paymentData.data"
                />
            </template>
            <button v-if="useMockApi" class="button primary" type="button" @click="processPayment">
                {{ translations.submit_to_mock_api }}
            </button>
            <div class="error">{{ errorMessage }}</div>
            <div v-if="paymentResponse">
                <div class="label">{{ translations.payment_response }}</div>
                <textarea
                    class="small"
                    :rows="10"
                    aria-autocomplete="none"
                    aria-multiline="false"
                    autocapitalize="off"
                    autocorrect="off"
                    data-enable-grammarly="false"
                    data-gramm="false"
                    spellcheck="false"
                    :value="paymentResponse"
                />
            </div>
        </div>
        <button class="button primary mt-1" type="button" @click="handleRestartSession">
            {{ translations.restart_session }}
        </button>
        <div class="flex column start mt-1">
            <span>{{ translations.to_learn_more_about_creating_payment_check_the_following_link }}</span>
            <a class="button link" :href="createPaymentApiDocumentationLink" target="_blank" rel="noopener noreferrer">
                {{ translations.create_payment_api_documentation }}
            </a>
            <a class="button link" :href="serverToServerDocumentationLink" target="_blank" rel="noopener noreferrer">
                {{ translations.server_to_server_integration }}
            </a>
        </div>
    </div>
</template>
