// examples/svelte/src/pages/FinalizePaymentPage.svelte
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script lang="ts">
    import { onMount } from 'svelte';
    import { goto } from '$app/navigation';
    import Logo from '../components/Logo/Logo.svelte';
    import Loader from '../components/Loader/Loader.svelte';
    import { loader } from '../stores/loader';
    import StorageService from '@shared/services/StorageService';
    import ApiService from '@shared/services/ApiService';
    import { mockApiUrl, useMockApi } from '../config';
    import { translations } from '../translations/translations';
    import { createPaymentApiDocumentationLink, serverToServerDocumentationLink } from '@shared/constants/links';
    import { type PaymentContextWithAmount } from 'onlinepayments-sdk-client-js';
    import type { CardPaymentSpecificData, CreatePaymentRequest } from '@shared/types/CreatePaymentRequest';
    import { resolve } from '$app/paths';

    type PaymentData = { type: 'encrypted' | 'raw'; data: string };

    let paymentContext: PaymentContextWithAmount | null = null;
    let paymentData: PaymentData | null = null;
    let paymentRequest: string = '';
    let paymentResponse: string = '';
    let errorMessage = '';

    onMount(() => {
        const paymentRequestData = StorageService.getPaymentRequest();
        const encryptedData = StorageService.getEncryptedData();
        const cardPaymentSpecificData = StorageService.getCardPaymentSpecificData();

        if (!paymentRequestData && !encryptedData && !cardPaymentSpecificData) {
            goto(resolve('/payment'));

            return;
        }

        paymentRequest = paymentRequestData ? JSON.stringify(paymentRequestData, null, 2) : '';

        if (cardPaymentSpecificData) {
            paymentData = { type: 'raw', data: JSON.stringify(cardPaymentSpecificData, null, 2) };
        } else {
            paymentData = { type: 'encrypted', data: encryptedData ?? '' };
        }

        if (StorageService.getPaymentContext()) {
            paymentContext = StorageService.getPaymentContext()!;
        }
    });

    /**
     * Sends the payment request to the API.
     * Determines whether to use encrypted data or raw card-specific data.
     * Updates the paymentResponse or errorMessage based on API response.
     */
    const processPayment = async (): Promise<void> => {
        errorMessage = '';
        paymentResponse = '';
        loader.show();

        const cardSpecific = StorageService.getCardPaymentSpecificData() as CardPaymentSpecificData | null;
        const accountOnFileId = StorageService.getAccountOnFileId();
        const encryptedData = StorageService.getEncryptedData();

        try {
            let payload: CreatePaymentRequest =
                cardSpecific && accountOnFileId
                    ? { ...cardSpecific, ...paymentContext }
                    : { data: encryptedData ?? '', ...paymentContext };

            const response = await ApiService(mockApiUrl).createPayment(payload);
            paymentResponse = JSON.stringify(response, null, 2);
        } catch (err: unknown) {
            const apiError = err as { errors?: { message: string }[] } | undefined;

            if (apiError?.errors?.length) {
                errorMessage =
                    translations.errors_while_fetching_data +
                    apiError.errors.map((e) => e.message).join(', ');
            } else {
                errorMessage =
                    translations.there_was_an_error_fetching_data_did_you_mock_api;
            }
        } finally {
            loader.hide();
        }
    };

    /**
     * Restarts the session by clearing all stored data and navigating back to the home page.
     */
    const handleRestartSession = async (): Promise<void> => {
        StorageService.clear();

        await goto(resolve('/'));
    };
</script>

<Loader />

<div class="page">
    <Logo />
    <h1>{translations.complete_payment}</h1>

    <div class="form">
        <div class="label">{translations.payment_request}</div>
        <textarea
            class="small"
            rows="10"
            spellcheck="false"
            readonly
        >{paymentRequest}</textarea>

        {#if paymentData}
            <div class="label">
                {paymentData.type === 'raw' ? 'Payload' : translations.encrypted_string}
            </div>
            <textarea
                class="small"
                rows="10"
                spellcheck="false"

            >{paymentData.data}</textarea>
        {/if}

        {#if useMockApi}
            <button class="button primary" type="button" on:click={processPayment}>
                {translations.submit_to_mock_api}
            </button>
        {/if}

        {#if errorMessage}
            <div class="error">{errorMessage}</div>
        {/if}

        {#if paymentResponse}
            <div>
                <div class="label">{translations.payment_response}</div>
                <textarea
                    class="small"
                    rows="10"
                    spellcheck="false"
                    readonly
                >{paymentResponse}</textarea>
            </div>
        {/if}
    </div>

    <button class="button primary mt-1" type="button" on:click={handleRestartSession}>
        {translations.restart_session}
    </button>

    <div class="flex column start mt-1">
        <span>{translations.to_learn_more_about_creating_payment_check_the_following_link}</span>
       <!--        eslint-disable-next-line svelte/no-navigation-without-resolve -->
        <a class="button link" href={createPaymentApiDocumentationLink} target="_blank"
           rel="noopener noreferrer">
            {translations.create_payment_api_documentation}
        </a>
        <!--        eslint-disable-next-line svelte/no-navigation-without-resolve -->
        <a class="button link" href={serverToServerDocumentationLink} target="_blank"
           rel="noopener noreferrer">
            {translations.server_to_server_integration}
        </a>
    </div>
</div>

// examples/vue/src/pages/FinalizePayment/FinalizePaymentPage.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import { onMounted, ref, shallowRef } from 'vue';
import { useRouter } from 'vue-router';
import {
    type ErrorResponse,
    init,
    type OnlinePaymentSdk,
    type PaymentContextWithAmount
} from 'onlinepayments-sdk-client-js';
import { mockApiUrl, useMockApi } from '../../config.ts';
import StorageService from '@shared/services/StorageService';
import ApiService from '@shared/services/ApiService';
import { createPaymentApiDocumentationLink, serverToServerDocumentationLink } from '@shared/constants/links';
import LoaderService from '../../services/LoaderService.ts';
import translations from '../../translations/translations';
import type { CardPaymentSpecificData, EncryptedData } from '@shared/types/CreatePaymentRequest';
import Logo from '../../components/Logo/Logo.vue';

type PaymentData = {
    type: 'encrypted' | 'raw';
    data: string;
};

const sdk = shallowRef<OnlinePaymentSdk>();

const router = useRouter();

const paymentContext = ref<PaymentContextWithAmount>();
const paymentData = ref<PaymentData>();
const paymentResponse = ref<string>('');
const errorMessage = ref<string>('');

const paymentRequest = ref<string>(JSON.stringify(StorageService.getPaymentRequest() ?? '', null, 2));

onMounted(() => {
    const sessionDetails = StorageService.getSessionData();
    const context = StorageService.getPaymentContext();
    const cardPaymentSpecificData = StorageService.getCardPaymentSpecificData();

    if (sessionDetails) {
        sdk.value = init(sessionDetails);
    }

    if (context) {
        paymentContext.value = context;
    }

    if (cardPaymentSpecificData) {
        paymentData.value = {
            type: 'raw',
            data: JSON.stringify(cardPaymentSpecificData, null, 2)
        };
    } else {
        paymentData.value = {
            type: 'encrypted',
            data: StorageService.getEncryptedData() ?? ''
        };
    }
});

const handleRestartSession = () => {
    StorageService.clear();
    router.push('/');
};

const processPayment = async () => {
    let message = '';

    LoaderService.show();
    ApiService(mockApiUrl)
        .createPayment({
            ...paymentContext.value,
            ...((StorageService.getCardPaymentSpecificData()
                ? ({ ...StorageService.getCardPaymentSpecificData() } as CardPaymentSpecificData)
                : { data: StorageService.getEncryptedData() }) as EncryptedData)
        })
        .then((response) => {
            paymentResponse.value = JSON.stringify(response, null, 2);
        })
        .catch((error: ErrorResponse) => {
            if (error.errors?.length) {
                message = translations.errors_while_fetching_data + error.errors.map((err) => err.message).join(', ');
            } else {
                message = translations.there_was_an_error_fetching_data_did_you_mock_api;
            }
        })
        .finally(() => {
            errorMessage.value = message;
            LoaderService.hide();
        });
};
</script>
<template>
    <div class="page">
        <Logo />
        <h1>{{ translations.complete_payment }}</h1>
        <div class="form">
            <div class="label">{{ translations.payment_request }}</div>
            <textarea
                class="small"
                :rows="10"
                aria-autocomplete="none"
                aria-multiline="true"
                autocapitalize="off"
                autocorrect="off"
                data-enable-grammarly="false"
                data-gramm="false"
                spellcheck="false"
                :value="paymentRequest"
            />
            <template v-if="paymentData">
                <div class="label">
                    {{ paymentData.type === 'raw' ? translations.payload : translations.encrypted_string }}
                </div>
                <textarea
                    class="small"
                    :rows="10"
                    aria-autocomplete="none"
                    aria-multiline="false"
                    autocapitalize="off"
                    autocorrect="off"
                    data-enable-grammarly="false"
                    data-gramm="false"
                    spellcheck="false"
                    :value="paymentData.data"
                />
            </template>
            <button v-if="useMockApi" class="button primary" type="button" @click="processPayment">
                {{ translations.submit_to_mock_api }}
            </button>
            <div class="error">{{ errorMessage }}</div>
            <div v-if="paymentResponse">
                <div class="label">{{ translations.payment_response }}</div>
                <textarea
                    class="small"
                    :rows="10"
                    aria-autocomplete="none"
                    aria-multiline="false"
                    autocapitalize="off"
                    autocorrect="off"
                    data-enable-grammarly="false"
                    data-gramm="false"
                    spellcheck="false"
                    :value="paymentResponse"
                />
            </div>
        </div>
        <button class="button primary mt-1" type="button" @click="handleRestartSession">
            {{ translations.restart_session }}
        </button>
        <div class="flex column start mt-1">
            <span>{{ translations.to_learn_more_about_creating_payment_check_the_following_link }}</span>
            <a class="button link" :href="createPaymentApiDocumentationLink" target="_blank" rel="noopener noreferrer">
                {{ translations.create_payment_api_documentation }}
            </a>
            <a class="button link" :href="serverToServerDocumentationLink" target="_blank" rel="noopener noreferrer">
                {{ translations.server_to_server_integration }}
            </a>
        </div>
    </div>
</template>
