// examples/angular/src/app/pages/session-page/session-page.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { Component, ElementRef, inject, signal, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { ErrorResponse, SessionData } from 'onlinepayments-sdk-client-js';
import { FormInput } from '../../components/form-elements/input/input';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { ApiService } from '../../services/api-service';
import { LogoComponent } from '../../components/logo/logo';
import StorageService from '@shared/services/StorageService';
import { useMockApi } from '../../../config';
import { LoaderService } from '../../services/loader-service';

type SessionDetailsForm = {
  assetUrl: FormControl<string>;
  customerId: FormControl<string>;
  clientApiUrl: FormControl<string>;
  clientSessionId: FormControl<string>;
};

@Component({
  selector: 'session-page',
  imports: [FormInput, ReactiveFormsModule, LogoComponent],
  templateUrl: './session-page.html',
  standalone: true,
})
export class SessionPage {
  apiService: ApiService = inject(ApiService);
  router = inject(Router);

  @ViewChild('sessionFormRef', { read: ElementRef })
  sessionFormRef!: ElementRef<HTMLFormElement>;

  sessionDetails = new FormGroup<SessionDetailsForm>({
    assetUrl: new FormControl<string>('', { nonNullable: true }),
    customerId: new FormControl<string>('', { nonNullable: true }),
    clientApiUrl: new FormControl<string>('', { nonNullable: true }),
    clientSessionId: new FormControl<string>('', { nonNullable: true }),
  });

  errorMessage = signal<string>('');

  constructor(private loader: LoaderService) {}

  ngOnInit() {
    const sessionDetails = StorageService.getSessionData();
    if (sessionDetails) {
      this.sessionDetails.patchValue(sessionDetails, {
        emitEvent: false,
      });
    }
  }

  handleSubmit() {
    this.sessionFormRef.nativeElement.reportValidity();
    if (this.sessionDetails.valid) {
      const newSessionDetails: SessionData = { ...this.sessionDetails.getRawValue() };

      StorageService.clear();
      StorageService.setSession(newSessionDetails);

      void this.router.navigate(['/payment']);
    }
  }

  pasteData() {
    navigator.clipboard.readText().then((text) => {
      try {
        const data = JSON.parse(text);
        if (data?.assetUrl && data.clientApiUrl && data.clientSessionId && data.customerId) {
          const newValue = {
            clientSessionId: data.clientSessionId,
            clientApiUrl: data.clientApiUrl,
            assetUrl: data.assetUrl,
            customerId: data.customerId,
          };
          this.sessionDetails.setValue(newValue, { emitEvent: false });
          return;
        }
      } catch (_) {
        this.errorMessage.set('The clipboard does not contain valid data.');
      }
    });
  }

  async fetchSessionFromAPI() {
    this.loader.show();
    this.apiService
      .getSession()
      .then((response) => {
        const sessionDetails: SessionData = {
          clientSessionId: response.clientSessionId,
          clientApiUrl: response.clientApiUrl,
          assetUrl: response.assetUrl,
          customerId: response.customerId,
        };

        this.sessionDetails.setValue(sessionDetails, { emitEvent: false });
      })
      .catch((error: ErrorResponse) => {
        if (error.errors?.length) {
          this.errorMessage.set(
            'Errors while fetching data: ' + error.errors.map((err) => err.message).join(', '),
          );
        } else {
          this.errorMessage.set('There was an error fetching data. Did you start the mock API?');
        }
      })
      .finally(() => {
        this.loader.hide();
      });
  }

  protected readonly useMockApi = useMockApi;
}

// examples/vue/src/pages/Session/SessionPage.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import translations from '../../translations/translations.ts';
import { mockApiUrl, useMockApi } from '../../config.ts';
import Logo from '../../components/Logo/Logo.vue';
import Input from '../../components/FormFields/Input/Input.vue';
import { type ErrorResponse, type SessionData } from 'onlinepayments-sdk-client-js';
import StorageService from '@shared/services/StorageService';
import ApiService from '@shared/services/ApiService';
import { useRouter } from 'vue-router';
import RouterService from '../../services/RouterService.ts';
import LoaderService from '../../services/LoaderService.ts';

const router = useRouter();
const { redirectToPage } = RouterService(router);

const SessionDetailsInitialData = {
    clientSessionId: '',
    assetUrl: '',
    customerId: '',
    clientApiUrl: ''
} satisfies SessionData;

const sessionDetailsModel: SessionData = reactive({ ...SessionDetailsInitialData });

const errorMessage = ref('');

onMounted(() => {
    const sessionDetails = StorageService.getSessionData();

    if (sessionDetails) {
        Object.assign(sessionDetailsModel, sessionDetails);
    }
});

const handleSubmit = () => {
    if (
        !sessionDetailsModel?.assetUrl ||
        !sessionDetailsModel.clientApiUrl ||
        !sessionDetailsModel.clientSessionId ||
        !sessionDetailsModel.customerId
    ) {
        errorMessage.value = translations.please_fill_in_all_the_data;
    } else {
        StorageService.clear();
        StorageService.setSession(sessionDetailsModel);

        redirectToPage('/payment');
    }
};

const fetchSessionFromAPI = async () => {
    LoaderService.show();
    let message = '';

    ApiService(mockApiUrl)
        .getSession()
        .then((response) => {
            Object.assign(sessionDetailsModel, response);
        })
        .catch((error: ErrorResponse) => {
            if (error.errors?.length) {
                message = translations.errors_while_fetching_data + error.errors.map((err) => err.message).join(', ');
            } else {
                message = translations.there_was_an_error_fetching_data_did_you_mock_api;
            }
        })
        .finally(() => {
            errorMessage.value = message;
            LoaderService.hide();
        });
};

const pasteData = () => {
    let error = '';

    navigator.clipboard.readText().then((text) => {
        try {
            const data = JSON.parse(text);
            if (data?.assetUrl && data.clientApiUrl && data.clientSessionId && data.customerId) {
                Object.assign(sessionDetailsModel, {
                    assetUrl: data.assetUrl,
                    clientApiUrl: data.clientApiUrl,
                    clientSessionId: data.clientSessionId,
                    customerId: data.customerId
                });
                return;
            }
        } catch {
            error = translations.the_clipboard_does_not_contain_valid_data;
        }
    });
    errorMessage.value = error;
};
</script>

<template>
    <div class="page">
        <Logo />
        <h1>{{ translations.initialize_session }}</h1>
        <p>
            {{
                translations.to_process_the_payment_using_services_provided_by_the_online_payments_platform +
                translations.information_must_be_provided_as_a_merchant
            }}
        </p>
        <div class="flex column mt-1">
            <form class="form" id="sessionForm" @submit.prevent="handleSubmit">
                <Input
                    id="asset-url"
                    :label="translations.asset_url"
                    required
                    v-model="sessionDetailsModel.assetUrl"
                    type="url"
                />
                <Input
                    id="client-api-url"
                    :label="translations.client_api_url"
                    required
                    v-model="sessionDetailsModel.clientApiUrl"
                    type="url"
                />
                <Input
                    id="client-session-id"
                    :label="translations.client_session_id"
                    required
                    v-model="sessionDetailsModel.clientSessionId"
                />
                <Input id="customer-id" label="Customer ID" required v-model="sessionDetailsModel.customerId" />
                <button class="button primary" type="submit">{{ translations.start_session }}</button>
            </form>
            <div class="label">{{ translations.get_session_details_from }}</div>
            <div class="flex row center">
                <button class="button" type="button" @click="pasteData">{{ translations.clipboard }}</button>
                <button v-if="useMockApi" class="button" type="button" @click="fetchSessionFromAPI">
                    {{ translations.mock_api }}
                </button>
            </div>
        </div>
        <div class="error mt-1" id="errorMessage">{{ errorMessage }}</div>
    </div>
</template>
