// examples/angular/src/app/components/header/header.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { Component } from '@angular/core';
import { ThemeSwitcher } from '../theme-switcher/theme-switcher';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'wl-header',
  imports: [ThemeSwitcher, RouterLink],
  templateUrl: './header.html',
  standalone: true,
})
export class Header {}

// examples/vue/src/components/Header/Header.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import ThemeSwitcher from '../ThemeSwitcher/ThemeSwitcher.vue';
</script>

<template>
    <header class="main-header small">
        <RouterLink class="button link" to="/">Home</RouterLink>
        <ThemeSwitcher />
    </header>
</template>
