// examples/svelte/src/components/AdditionalCardOperations/AdditionalCardOperations.svelte
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script lang="ts">
    import { translations } from '../../translations/translations';
    import type {
        AmountOfMoney,
        OnlinePaymentSdk,
        SdkError
    } from 'onlinepayments-sdk-client-js';
    import { loader } from '../../stores/loader';
    import ErrorService from '@shared/services/ErrorService';

    export let sdk: OnlinePaymentSdk | null = null;
    export let cardNumber: string = '';
    export let cardNumberError: boolean = false;
    export let paymentProductId: number | undefined = undefined;
    export let amountOfMoney: AmountOfMoney | undefined = undefined;

    let cardOperations = {
        currencyConversions: [] as string[],
        surcharges: [] as string[]
    };

    let cardOperationsErrors = {
        currencyConversions: [] as string[],
        surcharges: [] as string[]
    };

    /**
     * Removes all spaces from the card number.
     * @param number - Raw card number
     * @returns Sanitized card number
     */
    const sanitizeCardNumber = (number: string) => number.replaceAll(' ', '');

    /**
     * Process currency conversion using SDK session
     * @param cardNum - sanitized card number
     */
    const processCurrencyConversion = async (cardNum: string) => {
        if (!sdk) {
            return;
        }

        loader.show();

        try {
            const response = await sdk.getCurrencyConversionQuote(amountOfMoney!, {
                partialCreditCardNumber: cardNum,
                paymentProductId
            });

            if (response.result) {
                cardOperations = {
                    ...cardOperations,
                    currencyConversions: [
                        ...cardOperations.currencyConversions,
                        `${response.result.result} (${response.result.resultReason})`
                    ]
                };
            }

            if (response.proposal?.rate) {
                cardOperations = {
                    ...cardOperations,
                    currencyConversions: [
                        ...cardOperations.currencyConversions,
                        `Rate: ${response.proposal.rate.exchangeRate}`
                    ]
                };
            }
        } catch (err) {
            const error = err as SdkError;
            const errorMessages  = ErrorService.extractErrorMessages(error)
            if (errorMessages?.length) {
                cardOperationsErrors = {
                    ...cardOperationsErrors,
                    currencyConversions: [...cardOperationsErrors.currencyConversions, ...errorMessages]
                };
            }
        } finally {
            loader.hide();
        }
    };

    /** Handle click on the "Currency Conversion" button */
    const handleClickCurrencyConversion = async () => {
        cardOperationsErrors = { ...cardOperationsErrors, currencyConversions: [] };
        cardOperations = { ...cardOperations, currencyConversions: [] };

        const sanitized = sanitizeCardNumber(cardNumber);

        if (!cardNumberError && sanitized.length > 0) {
            await processCurrencyConversion(sanitized);
        } else {
            cardOperationsErrors = {
                ...cardOperationsErrors,
                currencyConversions: [translations.please_enter_the_card_number]
            };
        }
    };

    /**
     * Process surcharge using SDK session
     * @param cardNum - sanitized card number
     */
    const processSurcharge = async (cardNum: string) => {
        if (!sdk) {
            return;
        }

        loader.show();

        try {
            const response = await sdk.getSurchargeCalculation(amountOfMoney!, {
                partialCreditCardNumber: cardNum,
                paymentProductId
            });

            if (response.surcharges?.length) {
                const surcharges = response.surcharges
                    .filter(s => s.result === 'OK')
                    .map((s, index) => `${index + 1}: ${s.surchargeAmount.amount} ${s.surchargeAmount.currencyCode}`);

                cardOperations = { ...cardOperations, surcharges };
            }
        } catch (err) {
            const error = err as SdkError;
            const errorMessages = ErrorService.extractErrorMessages(error);

            if (errorMessages?.length) {
                cardOperationsErrors = {
                    ...cardOperationsErrors,
                    surcharges: [...cardOperationsErrors.surcharges, ...errorMessages]
                };
            }
        } finally {
            loader.hide();
        }
    };

    /** Handle click on the "Surcharge" button */
    const handleClickSurcharge = async () => {
        cardOperationsErrors = { ...cardOperationsErrors, surcharges: [] };
        cardOperations = { ...cardOperations, surcharges: [] };

        const sanitized = sanitizeCardNumber(cardNumber);

        if (!cardNumberError && sanitized.length > 0) {
            await processSurcharge(sanitized);
        } else {
            cardOperationsErrors = {
                ...cardOperationsErrors,
                surcharges: [translations.please_enter_the_card_number]
            };
        }
    };
</script>

<div class="additional-utils form">
    <h3 class="m-0">{translations.currency_conversion}</h3>
    <p class="text-left">{translations.this_utility_checks_weather_currency_conversion_can_be_applied_for_the_given_card}</p>
    <button class="button secondary small" on:click={handleClickCurrencyConversion}>
        {translations.get_quote}
    </button>

    {#each cardOperationsErrors.currencyConversions as msg, i (i)}
        <div class="text error">{msg}</div>
    {/each}

    {#each cardOperations.currencyConversions as msg, i (i)}
        <div class="text">{msg}</div>
    {/each}
</div>

<div class="additional-utils form">
    <h3 class="m-0">{translations.calculate_surcharge}</h3>
    <p class="text-left">{translations.this_utility_calculatest_the_surcharge_for_the_given_credit_card_if_enabled}</p>
    <button class="button secondary small" on:click={handleClickSurcharge}>
        {translations.calculate}
    </button>

    {#each cardOperationsErrors.surcharges as msg, i (i)}
        <div class="text error">{msg}</div>
    {/each}

    {#each cardOperations.surcharges as msg, i (i)}
        <div class="text">{msg}</div>
    {/each}
</div>

// examples/react/src/components/AdditionalCardOperations/AdditionalCardOperations.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import translations from '../../translations/translations.ts';
import { useState } from 'react';
import type { AmountOfMoney, OnlinePaymentSdk, SdkError } from 'onlinepayments-sdk-client-js';
import { useLoader } from '../Loader/Loader.tsx';
import ErrorService from '@shared/services/ErrorService.ts';

type CardOperations = {
    currencyConversions: string[];
    surcharges: string[];
};

type CardOperationsErrorMessages = {
    surcharges: string[];
    currencyConversions: string[];
};

const CardOperationsInitialState = {
    currencyConversions: [],
    surcharges: []
} satisfies CardOperations;

const CardOperationsErrorInitialState = {
    currencyConversions: [],
    surcharges: []
};

type Props = {
    sdk: OnlinePaymentSdk | null;
    cardNumber: string;
    cardNumberError: boolean;
    paymentProductId?: number;
    amountOfMoney: AmountOfMoney;
};
const AdditionalCardOperations = ({ sdk, cardNumber, cardNumberError, paymentProductId, amountOfMoney }: Props) => {
    const { show, hide } = useLoader();

    const [cardOperations, setCardOperations] = useState<CardOperations>({ ...CardOperationsInitialState });
    const [cardOperationsErrors, setCardOperationsErrors] = useState<CardOperationsErrorMessages>({
        ...CardOperationsErrorInitialState
    });

    const handleClickSurcharge = () => {
        setCardOperationsErrors((prev) => ({
            ...prev,
            surcharges: []
        }));

        if (!cardNumberError && cardNumber.replaceAll(' ', '').length > 0) {
            processSurcharge(cardNumber.replaceAll(' ', ''));
        } else {
            setCardOperationsErrors((prev) => ({
                ...prev,
                surcharges: [...prev.surcharges, translations.please_enter_the_card_number]
            }));
        }
    };

    const processSurcharge = (cardNumber: string) => {
        show();

        sdk?.getSurchargeCalculation(amountOfMoney, {
            partialCreditCardNumber: cardNumber,
            paymentProductId: paymentProductId
        })
            .then((response) => {
                if (response.surcharges?.length) {
                    response.surcharges.forEach((surcharge, index) => {
                        if (surcharge.result === 'OK') {
                            setCardOperations((prev) => ({
                                ...prev,
                                surcharge: `${index + 1}: ${surcharge.surchargeAmount.amount} ${surcharge.surchargeAmount.currencyCode}`
                            }));
                        }
                    });
                }
            })
            .catch((error: SdkError) => {
                const errorMessages = ErrorService.extractErrorMessages(error);

                setCardOperationsErrors((prev) => ({
                    ...prev,
                    surcharges: [...prev.surcharges, ...errorMessages]
                }));
            })
            .finally(() => {
                hide();
            });
    };

    const handleClickCurrencyConversion = () => {
        setCardOperationsErrors((prev) => ({
            ...prev,
            currencyConversions: []
        }));

        if (!cardNumberError && cardNumber.replaceAll(' ', '').length > 0) {
            processCurrencyConversion(cardNumber.replaceAll(' ', ''));
        } else {
            setCardOperationsErrors((prev) => ({
                ...prev,
                currencyConversions: [...prev.currencyConversions, translations.please_enter_the_card_number]
            }));
        }
    };

    const processCurrencyConversion = (cardNumber: string) => {
        show();

        sdk?.getCurrencyConversionQuote(amountOfMoney, {
            partialCreditCardNumber: cardNumber,
            paymentProductId: paymentProductId
        })
            .then((response) => {
                if (response.result) {
                    setCardOperations((prev) => ({
                        ...prev,
                        currencyConversions: [
                            ...prev.currencyConversions,
                            `${response.result.result} (${response.result.resultReason})`
                        ]
                    }));
                }

                if (response.proposal?.rate) {
                    setCardOperations((prev) => ({
                        ...prev,
                        currencyConversions: [
                            ...prev.currencyConversions,
                            ` Rate: ${response.proposal.rate.exchangeRate}`
                        ]
                    }));
                }
            })
            .catch((error: SdkError) => {
                const errorMessages = ErrorService.extractErrorMessages(error);

                setCardOperationsErrors((prev) => ({
                    ...prev,
                    currencyConversions: [...prev.currencyConversions, ...errorMessages]
                }));
            })
            .finally(() => {
                hide();
            });
    };

    return (
        <>
            <div className='additional-utils form'>
                <h3 className='m-0'>{translations.currency_conversion}</h3>
                <p className='text-left'>
                    {translations.this_utility_checks_weather_currency_conversion_can_be_applied_for_the_given_card}
                </p>
                <button className='button secondary small' onClick={handleClickCurrencyConversion}>
                    {translations.get_quote}
                </button>
                <div className='text-left error'>
                    {cardOperationsErrors.currencyConversions?.length > 0 &&
                        cardOperationsErrors.currencyConversions.map((currencyConversion, key) => (
                            <div className='text' key={key}>
                                {currencyConversion}
                            </div>
                        ))}
                </div>
                <div className='field'>
                    {cardOperations.currencyConversions?.length > 0 &&
                        cardOperations.currencyConversions.map((currencyConversion, key) => (
                            <div className='text' key={key}>
                                {currencyConversion}
                            </div>
                        ))}
                </div>
            </div>
            <div className='additional-utils form'>
                <h3 className='m-0'>{translations.calculate_surcharge}</h3>
                <p className='text-left'>
                    {translations.this_utility_calculatest_the_surcharge_for_the_given_credit_card_if_enabled}
                </p>
                <button className='button secondary small' onClick={handleClickSurcharge}>
                    {translations.calculate}
                </button>
                <div className='text-left error'>
                    {cardOperationsErrors.surcharges?.length > 0 &&
                        cardOperationsErrors.surcharges.map((surcharge, key) => (
                            <div className='text' key={key}>
                                {surcharge}
                            </div>
                        ))}
                </div>
                <div className='field'>
                    {cardOperations.surcharges?.length > 0 &&
                        cardOperations.surcharges.map((surcharge, key) => (
                            <div className='text' key={key}>
                                {surcharge}
                            </div>
                        ))}
                </div>
            </div>
        </>
    );
};

export default AdditionalCardOperations;
