// examples/angular/src/app/components/additional-card-operations/additional-card-operations.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { Component, Input, signal } from '@angular/core';
import { AmountOfMoney, type OnlinePaymentSdk, SdkError } from 'onlinepayments-sdk-client-js';
import { LoaderService } from '../../services/loader-service';
import ErrorService from '@shared/services/ErrorService';

type CardOperations = {
  currencyConversions: string[];
  surcharges: string[];
};

type CardOperationsErrorMessages = {
  currencyConversions: string[];
  surcharges: string[];
};

@Component({
  selector: 'additional-card-operations',
  imports: [],
  standalone: true,
  templateUrl: './additional-card-operations.html',
  styleUrls: ['./additional-card-operations.css'],
})
export class AdditionalCardOperations {
  @Input() sdk: OnlinePaymentSdk | null = null;
  @Input() cardNumber = '';
  @Input() cardNumberError = false;
  @Input() paymentProductId?: number;
  @Input({ required: true }) amountOfMoney!: AmountOfMoney;

  cardOperations = signal<CardOperations>({
    currencyConversions: [],
    surcharges: [],
  });

  cardOperationsErrors = signal<CardOperationsErrorMessages>({
    currencyConversions: [],
    surcharges: [],
  });

  constructor(private loader: LoaderService) {}

  handleClickCurrencyConversion(): void {
    this.cardOperationsErrors.update((prev) => ({ ...prev, currencyConversions: [] }));

    const trimmedCardNumber = this.cardNumber.replaceAll(' ', '');

    if (!this.cardNumberError && trimmedCardNumber.length > 0) {
      this.processCurrencyConversion(trimmedCardNumber);
    } else {
      this.cardOperationsErrors.update((prev) => ({
        ...prev,
        currencyConversions: [...prev.currencyConversions, 'Please enter the card number.'],
      }));
    }
  }

  private processCurrencyConversion(cardNumber: string): void {
    this.loader.show();

    this.sdk
      ?.getCurrencyConversionQuote(this.amountOfMoney, {
        partialCreditCardNumber: cardNumber,
        paymentProductId: this.paymentProductId,
      })
      .then((response) => {
        if (response?.result) {
          this.cardOperations.update((prev) => ({
            ...prev,
            currencyConversions: [
              ...prev.currencyConversions,
              `${response.result.result} (${response.result.resultReason})`,
            ],
          }));
        }
        if (response?.proposal?.rate?.exchangeRate) {
          this.cardOperations.update((prev) => ({
            ...prev,
            currencyConversions: [
              ...prev.currencyConversions,
              ` Rate: ${response.proposal.rate.exchangeRate}`,
            ],
          }));
        }
      })
      .catch((error: SdkError) => {
        const errorMessages = ErrorService.extractErrorMessages(error);
        if (errorMessages.length) {
          this.cardOperationsErrors.update((prev) => ({
            ...prev,
            currencyConversions: [...prev.currencyConversions, ...errorMessages],
          }));
        }
      })
      .finally(() => {
        this.loader.hide();
      });
  }

  handleClickSurcharge(): void {
    this.cardOperationsErrors.update((prev) => ({ ...prev, surcharges: [] }));

    const trimmedCardNumber = this.cardNumber.replaceAll(' ', '');

    if (!this.cardNumberError && trimmedCardNumber.length > 0) {
      this.processSurcharge(trimmedCardNumber);
    } else {
      this.cardOperationsErrors.update((prev) => ({
        ...prev,
        surcharges: [...prev.surcharges, 'Please enter the card number.'],
      }));
    }
  }

  private processSurcharge(cardNumber: string): void {
    this.loader.show();

    this.sdk
      ?.getSurchargeCalculation(this.amountOfMoney, {
        partialCreditCardNumber: cardNumber,
        paymentProductId: this.paymentProductId,
      })
      .then((response) => {
        if (Array.isArray(response?.surcharges) && response.surcharges.length) {
          const items: string[] = [];
          response.surcharges.forEach((surcharge: any, index: number) => {
            if (surcharge?.result === 'OK' && surcharge?.surchargeAmount) {
              items.push(
                `Surcharge ${index + 1}: ${surcharge.surchargeAmount.amount} ${surcharge.surchargeAmount.currencyCode}`,
              );
            }
          });

          if (items.length) {
            this.cardOperations.update((prev) => ({
              ...prev,
              surcharges: [...prev.surcharges, ...items],
            }));
          }
        }
      })
      .catch((error: SdkError) => {
        const errorMessages = ErrorService.extractErrorMessages(error);
        if (errorMessages.length) {
          this.cardOperationsErrors.update((prev) => ({
            ...prev,
            surcharges: [...prev.surcharges, ...errorMessages],
          }));
        }
      })
      .finally(() => {
        this.loader.hide();
      });
  }
}

// examples/react/src/components/AdditionalCardOperations/AdditionalCardOperations.tsx
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import translations from '../../translations/translations.ts';
import { useState } from 'react';
import type { AmountOfMoney, OnlinePaymentSdk, SdkError } from 'onlinepayments-sdk-client-js';
import { useLoader } from '../Loader/Loader.tsx';
import ErrorService from '@shared/services/ErrorService.ts';

type CardOperations = {
    currencyConversions: string[];
    surcharges: string[];
};

type CardOperationsErrorMessages = {
    surcharges: string[];
    currencyConversions: string[];
};

const CardOperationsInitialState = {
    currencyConversions: [],
    surcharges: []
} satisfies CardOperations;

const CardOperationsErrorInitialState = {
    currencyConversions: [],
    surcharges: []
};

type Props = {
    sdk: OnlinePaymentSdk | null;
    cardNumber: string;
    cardNumberError: boolean;
    paymentProductId?: number;
    amountOfMoney: AmountOfMoney;
};
const AdditionalCardOperations = ({ sdk, cardNumber, cardNumberError, paymentProductId, amountOfMoney }: Props) => {
    const { show, hide } = useLoader();

    const [cardOperations, setCardOperations] = useState<CardOperations>({ ...CardOperationsInitialState });
    const [cardOperationsErrors, setCardOperationsErrors] = useState<CardOperationsErrorMessages>({
        ...CardOperationsErrorInitialState
    });

    const handleClickSurcharge = () => {
        setCardOperationsErrors((prev) => ({
            ...prev,
            surcharges: []
        }));

        if (!cardNumberError && cardNumber.replaceAll(' ', '').length > 0) {
            processSurcharge(cardNumber.replaceAll(' ', ''));
        } else {
            setCardOperationsErrors((prev) => ({
                ...prev,
                surcharges: [...prev.surcharges, translations.please_enter_the_card_number]
            }));
        }
    };

    const processSurcharge = (cardNumber: string) => {
        show();

        sdk?.getSurchargeCalculation(amountOfMoney, {
            partialCreditCardNumber: cardNumber,
            paymentProductId: paymentProductId
        })
            .then((response) => {
                if (response.surcharges?.length) {
                    response.surcharges.forEach((surcharge, index) => {
                        if (surcharge.result === 'OK') {
                            setCardOperations((prev) => ({
                                ...prev,
                                surcharge: `${index + 1}: ${surcharge.surchargeAmount.amount} ${surcharge.surchargeAmount.currencyCode}`
                            }));
                        }
                    });
                }
            })
            .catch((error: SdkError) => {
                const errorMessages = ErrorService.extractErrorMessages(error);

                setCardOperationsErrors((prev) => ({
                    ...prev,
                    surcharges: [...prev.surcharges, ...errorMessages]
                }));
            })
            .finally(() => {
                hide();
            });
    };

    const handleClickCurrencyConversion = () => {
        setCardOperationsErrors((prev) => ({
            ...prev,
            currencyConversions: []
        }));

        if (!cardNumberError && cardNumber.replaceAll(' ', '').length > 0) {
            processCurrencyConversion(cardNumber.replaceAll(' ', ''));
        } else {
            setCardOperationsErrors((prev) => ({
                ...prev,
                currencyConversions: [...prev.currencyConversions, translations.please_enter_the_card_number]
            }));
        }
    };

    const processCurrencyConversion = (cardNumber: string) => {
        show();

        sdk?.getCurrencyConversionQuote(amountOfMoney, {
            partialCreditCardNumber: cardNumber,
            paymentProductId: paymentProductId
        })
            .then((response) => {
                if (response.result) {
                    setCardOperations((prev) => ({
                        ...prev,
                        currencyConversions: [
                            ...prev.currencyConversions,
                            `${response.result.result} (${response.result.resultReason})`
                        ]
                    }));
                }

                if (response.proposal?.rate) {
                    setCardOperations((prev) => ({
                        ...prev,
                        currencyConversions: [
                            ...prev.currencyConversions,
                            ` Rate: ${response.proposal.rate.exchangeRate}`
                        ]
                    }));
                }
            })
            .catch((error: SdkError) => {
                const errorMessages = ErrorService.extractErrorMessages(error);

                setCardOperationsErrors((prev) => ({
                    ...prev,
                    currencyConversions: [...prev.currencyConversions, ...errorMessages]
                }));
            })
            .finally(() => {
                hide();
            });
    };

    return (
        <>
            <div className='additional-utils form'>
                <h3 className='m-0'>{translations.currency_conversion}</h3>
                <p className='text-left'>
                    {translations.this_utility_checks_weather_currency_conversion_can_be_applied_for_the_given_card}
                </p>
                <button className='button secondary small' onClick={handleClickCurrencyConversion}>
                    {translations.get_quote}
                </button>
                <div className='text-left error'>
                    {cardOperationsErrors.currencyConversions?.length > 0 &&
                        cardOperationsErrors.currencyConversions.map((currencyConversion, key) => (
                            <div className='text' key={key}>
                                {currencyConversion}
                            </div>
                        ))}
                </div>
                <div className='field'>
                    {cardOperations.currencyConversions?.length > 0 &&
                        cardOperations.currencyConversions.map((currencyConversion, key) => (
                            <div className='text' key={key}>
                                {currencyConversion}
                            </div>
                        ))}
                </div>
            </div>
            <div className='additional-utils form'>
                <h3 className='m-0'>{translations.calculate_surcharge}</h3>
                <p className='text-left'>
                    {translations.this_utility_calculatest_the_surcharge_for_the_given_credit_card_if_enabled}
                </p>
                <button className='button secondary small' onClick={handleClickSurcharge}>
                    {translations.calculate}
                </button>
                <div className='text-left error'>
                    {cardOperationsErrors.surcharges?.length > 0 &&
                        cardOperationsErrors.surcharges.map((surcharge, key) => (
                            <div className='text' key={key}>
                                {surcharge}
                            </div>
                        ))}
                </div>
                <div className='field'>
                    {cardOperations.surcharges?.length > 0 &&
                        cardOperations.surcharges.map((surcharge, key) => (
                            <div className='text' key={key}>
                                {surcharge}
                            </div>
                        ))}
                </div>
            </div>
        </>
    );
};

export default AdditionalCardOperations;
