// examples/vue/src/pages/FinalizePayment/FinalizePaymentPage.vue
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
<script setup lang="ts">
import { onMounted, ref, shallowRef } from 'vue';
import { useRouter } from 'vue-router';
import {
    type ErrorResponse,
    init,
    type OnlinePaymentSdk,
    type PaymentContextWithAmount
} from 'onlinepayments-sdk-client-js';
import { mockApiUrl, useMockApi } from '../../config.ts';
import StorageService from '@shared/services/StorageService';
import ApiService from '@shared/services/ApiService';
import { createPaymentApiDocumentationLink, serverToServerDocumentationLink } from '@shared/constants/links';
import LoaderService from '../../services/LoaderService.ts';
import translations from '../../translations/translations';
import type { CardPaymentSpecificData, EncryptedData } from '@shared/types/CreatePaymentRequest';
import Logo from '../../components/Logo/Logo.vue';

type PaymentData = {
    type: 'encrypted' | 'raw';
    data: string;
};

const sdk = shallowRef<OnlinePaymentSdk>();

const router = useRouter();

const paymentContext = ref<PaymentContextWithAmount>();
const paymentData = ref<PaymentData>();
const paymentResponse = ref<string>('');
const errorMessage = ref<string>('');

const paymentRequest = ref<string>(JSON.stringify(StorageService.getPaymentRequest() ?? '', null, 2));

onMounted(() => {
    const sessionDetails = StorageService.getSessionData();
    const context = StorageService.getPaymentContext();
    const cardPaymentSpecificData = StorageService.getCardPaymentSpecificData();

    if (sessionDetails) {
        sdk.value = init(sessionDetails);
    }

    if (context) {
        paymentContext.value = context;
    }

    if (cardPaymentSpecificData) {
        paymentData.value = {
            type: 'raw',
            data: JSON.stringify(cardPaymentSpecificData, null, 2)
        };
    } else {
        paymentData.value = {
            type: 'encrypted',
            data: StorageService.getEncryptedData() ?? ''
        };
    }
});

const handleRestartSession = () => {
    StorageService.clear();
    router.push('/');
};

const processPayment = async () => {
    let message = '';

    LoaderService.show();
    ApiService(mockApiUrl)
        .createPayment({
            ...paymentContext.value,
            ...((StorageService.getCardPaymentSpecificData()
                ? ({ ...StorageService.getCardPaymentSpecificData() } as CardPaymentSpecificData)
                : { data: StorageService.getEncryptedData() }) as EncryptedData)
        })
        .then((response) => {
            paymentResponse.value = JSON.stringify(response, null, 2);
        })
        .catch((error: ErrorResponse) => {
            if (error.errors?.length) {
                message = translations.errors_while_fetching_data + error.errors.map((err) => err.message).join(', ');
            } else {
                message = translations.there_was_an_error_fetching_data_did_you_mock_api;
            }
        })
        .finally(() => {
            errorMessage.value = message;
            LoaderService.hide();
        });
};
</script>
<template>
    <div class="page">
        <Logo />
        <h1>{{ translations.complete_payment }}</h1>
        <div class="form">
            <div class="label">{{ translations.payment_request }}</div>
            <textarea
                class="small"
                :rows="10"
                aria-autocomplete="none"
                aria-multiline="true"
                autocapitalize="off"
                autocorrect="off"
                data-enable-grammarly="false"
                data-gramm="false"
                spellcheck="false"
                :value="paymentRequest"
            />
            <template v-if="paymentData">
                <div class="label">
                    {{ paymentData.type === 'raw' ? translations.payload : translations.encrypted_string }}
                </div>
                <textarea
                    class="small"
                    :rows="10"
                    aria-autocomplete="none"
                    aria-multiline="false"
                    autocapitalize="off"
                    autocorrect="off"
                    data-enable-grammarly="false"
                    data-gramm="false"
                    spellcheck="false"
                    :value="paymentData.data"
                />
            </template>
            <button v-if="useMockApi" class="button primary" type="button" @click="processPayment">
                {{ translations.submit_to_mock_api }}
            </button>
            <div class="error">{{ errorMessage }}</div>
            <div v-if="paymentResponse">
                <div class="label">{{ translations.payment_response }}</div>
                <textarea
                    class="small"
                    :rows="10"
                    aria-autocomplete="none"
                    aria-multiline="false"
                    autocapitalize="off"
                    autocorrect="off"
                    data-enable-grammarly="false"
                    data-gramm="false"
                    spellcheck="false"
                    :value="paymentResponse"
                />
            </div>
        </div>
        <button class="button primary mt-1" type="button" @click="handleRestartSession">
            {{ translations.restart_session }}
        </button>
        <div class="flex column start mt-1">
            <span>{{ translations.to_learn_more_about_creating_payment_check_the_following_link }}</span>
            <a class="button link" :href="createPaymentApiDocumentationLink" target="_blank" rel="noopener noreferrer">
                {{ translations.create_payment_api_documentation }}
            </a>
            <a class="button link" :href="serverToServerDocumentationLink" target="_blank" rel="noopener noreferrer">
                {{ translations.server_to_server_integration }}
            </a>
        </div>
    </div>
</template>

// examples/angular/src/app/pages/finalize-payment-page/finalize-payment-page.ts
/*
 * Do not remove or alter the notices in this preamble.
 *
 * This software is owned by Worldline and may not be be altered, copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, without the prior written consent of Worldline.
 *
 * Copyright © 2026 Worldline and/or its affiliates.
 *
 * All rights reserved. License grant and user rights and obligations according to the applicable license agreement.
 *
 * Please contact Worldline for questions regarding license and user rights.
 */
import { Component, inject, signal } from '@angular/core';
import { ApiService } from '../../services/api-service';
import StorageService from '@shared/services/StorageService';
import { Router } from '@angular/router';
import {
  ErrorResponse,
  init,
  type OnlinePaymentSdk,
  PaymentContextWithAmount,
  PaymentProduct,
} from 'onlinepayments-sdk-client-js';
import { useMockApi } from '../../../config';
import { LogoComponent } from '../../components/logo/logo';
import { LoaderService } from '../../services/loader-service';
import PaymentProductService from '@shared/services/PaymentProductService';

type PaymentData = {
  type: 'encrypted' | 'raw';
  data: string;
};

@Component({
  selector: 'app-finalize-payment-page',
  imports: [LogoComponent],
  templateUrl: './finalize-payment-page.html',
  standalone: true,
})
export class FinalizePaymentPage {
  router = inject(Router);
  apiService: ApiService = inject(ApiService);

  sdk: OnlinePaymentSdk | null = null;
  paymentProduct: PaymentProduct | null = null;
  paymentContext: PaymentContextWithAmount | null = StorageService.getPaymentContext();

  paymentResponse = signal('');
  paymentData = signal<PaymentData | null>(null);
  errorMessage = signal('');

  constructor(private loader: LoaderService) {}

  async initData(): Promise<void> {
    this.sdk = init(StorageService.getSessionData()!);

    this.paymentProduct = await PaymentProductService.getPaymentProduct(
      this.sdk,
      Number(StorageService.getPaymentProductId()!),
      StorageService.getPaymentContext()!,
    );

    if (StorageService.getEncryptedData()) {
      this.paymentData.set({
        type: 'encrypted',
        data: StorageService.getEncryptedData()!,
      });
    } else {
      this.paymentData.set({
        type: 'raw',
        data: JSON.stringify(StorageService.getCardPaymentSpecificData(), null, 2),
      });
    }
  }

  ngOnInit() {
    this.initData().catch((error) => console.log(error));
  }

  ngOnDestroy() {
    StorageService.clearItem('encryptedData');
    StorageService.clearItem('cardPaymentSpecificData');
  }

  handleRestartSession(): void {
    StorageService.clear();
    void this.router.navigate(['/']);
  }

  async processPayment(): Promise<void> {
    let errorMessage = '';
    this.loader.show();

    this.apiService
      .createPayment({
        ...this.paymentContext,
        ...(StorageService.getCardPaymentSpecificData()
          ? { ...StorageService.getCardPaymentSpecificData()! }
          : { data: StorageService.getEncryptedData()! }),
      })
      .then((response) => {
        this.paymentResponse.set(JSON.stringify(response, null, 2));
      })
      .catch((error: ErrorResponse) => {
        if (error.errors?.length) {
          errorMessage =
            'Errors while submitting the data: ' +
            error.errors.map((err) => err.message).join(', ');
        } else {
          errorMessage = 'There was an error fetching data. Did you start the Mock API?';
        }
      })
      .finally(() => {
        this.errorMessage.set(errorMessage);
        this.loader.hide();
      });
  }

  getPaymentRequestInfo() {
    return JSON.stringify(StorageService.getPaymentRequest(), null, 2);
  }

  protected readonly useMockApi = useMockApi;
  protected readonly StorageService = StorageService;
}
